import {Box, Button, FormHelperText, Grid, Stack, Typography} from '@mui/material';
import {alpha} from '@mui/material/styles';
import {useEffect, useMemo, useState} from 'react';
import Add from '@aivot/mui-material-symbols-400-n25-outlined/Add';
import Delete from '@aivot/mui-material-symbols-400-n25-outlined/Delete';
import Receipt from '@aivot/mui-material-symbols-400-n25-outlined/Receipt';
import {BaseViewProps} from './base-view';
import {
    PaymentConfigElement,
    PaymentConfigElementValue,
    PaymentConfigElementValueItem,
    PaymentConfigElementValueItemCostType,
    PaymentConfigElementValueItemIdType,
    PaymentConfigElementValueItemQuantityType,
    PaymentConfigElementValueItemVariableValueCalculationType,
    PaymentConfigElementValueRequestorMapping,
} from '../models/elements/form/input/payment-config-element';
import {PaymentProvidersApiService} from '../modules/payment/payment-providers-api-service';
import {PaymentProviderResponseDTO} from '../modules/payment/dtos/payment-provider-response-dto';
import {isApiError} from '../models/api-error';
import {hasDerivableAspects} from '../utils/has-derivable-aspects';
import {SelectFieldComponent, SelectFieldComponentOption} from '../components/select-field-2/select-field-component';
import {TextFieldComponent} from '../components/text-field/text-field-component';
import {CheckboxFieldComponent} from '../components/checkbox-field/checkbox-field-component';
import {NumberFieldComponent} from '../components/number-field/number-field-component';
import {ElementEditorSectionHeader} from '../components/element-editor-section-header/element-editor-section-header';
import {DialogList, DialogListPropsDialogContentComponent} from '../components/dialog-list/dialog-list';
import {isStringNullOrEmpty} from '../utils/string-utils';
import {ProcessDataKeyInputComponent} from './process-data-key-input-field-view';
import {NoCodeInputFieldComponent} from '../components/no-code-input-field/no-code-input-field-component';
import {NoCodeDataType} from '../data/no-code-data-type';
import {CodeInputFieldComponent} from '../components/code-input-field/code-input-field-component';
import {isFormLayoutElement} from '../models/elements/form-layout-element';
import {useViewDispatcherContext} from '../components/view-dispatcher/view-dispatcher.context';
import {AnyElement} from '../models/elements/any-element';
import {NoCodeOperand} from '../models/functions/no-code-expression';
import {JavascriptCode} from '../models/functions/javascript-code';

const FormLayoutFieldKey = 'formLayout';

const EmptyPaymentConfigValue: PaymentConfigElementValue = {
    paymentProviderKey: null,
    purpose: null,
    description: null,
    mapRequestor: false,
    requestorMapping: null,
    items: [],
};

const EmptyRequestorMapping: PaymentConfigElementValueRequestorMapping = {
    lastNameDestinationKey: null,
    firstNameDestinationKey: null,
    genderDestinationKey: null,
    isOrganizationDestinationKey: null,
    organizationNameDestinationKey: null,
    streeDestinationKey: null,
    houseNumberDestinationKey: null,
    addressLineDestinationKey: null,
    postalCodeDestinationKey: null,
    cityDestinationKey: null,
    countryDestinationKey: null,
};

const CostTypeOptions: SelectFieldComponentOption<PaymentConfigElementValueItemCostType>[] = [
    {label: 'Fester Betrag', value: PaymentConfigElementValueItemCostType.FixedCosts},
    {label: 'Berechneter Betrag', value: PaymentConfigElementValueItemCostType.VariableCosts},
];

const QuantityTypeOptions: SelectFieldComponentOption<PaymentConfigElementValueItemQuantityType>[] = [
    {label: 'Feste Menge', value: PaymentConfigElementValueItemQuantityType.FixedQuantity},
    {label: 'Berechnete Menge', value: PaymentConfigElementValueItemQuantityType.VariableQuantity},
];

const CalculationTypeOptions: SelectFieldComponentOption<PaymentConfigElementValueItemVariableValueCalculationType>[] = [
    {label: 'No-Code', value: PaymentConfigElementValueItemVariableValueCalculationType.NoCode},
    {label: 'Low-Code', value: PaymentConfigElementValueItemVariableValueCalculationType.LowCode},
];

const IdTypeOptions: SelectFieldComponentOption<PaymentConfigElementValueItemIdType>[] = [
    {label: 'Automatisch erzeugen', value: PaymentConfigElementValueItemIdType.AutoGeneratedUUID},
    {label: 'Fest vorgeben', value: PaymentConfigElementValueItemIdType.Predefined},
];

type PaymentItemRow = {
    index: number;
    item: PaymentConfigElementValueItem;
};

export function PaymentConfigView(props: BaseViewProps<PaymentConfigElement, PaymentConfigElementValue>) {
    const {
        element,
        value,
        setValue,
        errors,
        isBusy: isGloballyDisabled,
        isDeriving,
        authoredElementValues,
    } = props;

    const {
        rootElement,
    } = useViewDispatcherContext();

    const [providers, setProviders] = useState<PaymentProviderResponseDTO[]>([]);
    const [providersError, setProvidersError] = useState<string>();
    const [isLoadingProviders, setIsLoadingProviders] = useState(false);

    useEffect(() => {
        setIsLoadingProviders(true);

        new PaymentProvidersApiService()
            .listAll()
            .then((res) => {
                setProviders(res.content);
            })
            .catch((err) => {
                if (isApiError(err) && err.displayableToUser) {
                    setProvidersError(err.message);
                } else {
                    setProvidersError('Beim Abruf der Zahlungsdienstleister ist ein unbekannter Fehler aufgetreten.');
                }
            })
            .finally(() => {
                setIsLoadingProviders(false);
            });
    }, []);

    const currentValue = useMemo(() => normalizePaymentConfigValue(value), [value]);

    const isDisabled = useMemo(() => {
        return Boolean(element.disabled) || isGloballyDisabled;
    }, [element.disabled, isGloballyDisabled]);

    const isFieldBusy = useMemo(() => {
        return (isDeriving && hasDerivableAspects(element)) || isLoadingProviders;
    }, [element, isDeriving, isLoadingProviders]);

    const paymentProviderOptions = useMemo(() => {
        const options = [...providers]
            .sort((left, right) => Number(right.isEnabled) - Number(left.isEnabled) || left.name.localeCompare(right.name, 'de'))
            .map((provider) => ({
                label: provider.name,
                subLabel: [
                    provider.isEnabled ? undefined : 'Deaktiviert',
                    provider.isTestProvider ? 'Testanbieter' : undefined,
                    provider.description,
                ].filter((part) => part != null && part.length > 0).join(' · '),
                value: provider.key,
            }));

        if (
            currentValue.paymentProviderKey != null &&
            !options.some((option) => option.value === currentValue.paymentProviderKey)
        ) {
            options.push({
                label: `Ausgewählter Zahlungsdienstleister (${currentValue.paymentProviderKey})`,
                subLabel: 'Nicht gefunden',
                value: currentValue.paymentProviderKey,
            });
        }

        return options;
    }, [currentValue.paymentProviderKey, providers]);

    const calculationRootElement = useMemo<AnyElement>(() => {
        const configuredFormLayout = authoredElementValues[FormLayoutFieldKey];
        return isFormLayoutElement(configuredFormLayout) ? configuredFormLayout : rootElement;
    }, [authoredElementValues, rootElement]);

    const itemRows = useMemo<PaymentItemRow[]>(() => {
        return (currentValue.items ?? [])
            .map((item, index) => ({index, item}));
    }, [currentValue.items]);

    const ItemDialogContent = useMemo(() => {
        return wrapPaymentConfigItem(calculationRootElement);
    }, [calculationRootElement]);

    const updateValue = (patch: Partial<PaymentConfigElementValue>) => {
        const nextValue = {
            ...currentValue,
            ...patch,
        };

        setValue(isPaymentConfigValueEmpty(nextValue) ? null : nextValue);
    };

    const updateRequestorMapping = (
        field: keyof PaymentConfigElementValueRequestorMapping,
        fieldValue: string | null,
    ) => {
        updateValue({
            mapRequestor: true,
            requestorMapping: {
                ...EmptyRequestorMapping,
                ...currentValue.requestorMapping,
                [field]: fieldValue,
            },
        });
    };

    const handleAddItem = () => {
        updateValue({
            items: [
                ...(currentValue.items ?? []),
                createPaymentItem(),
            ],
        });
    };

    const handleItemChanged = (edited: PaymentItemRow, original: PaymentItemRow) => {
        const items = [...(currentValue.items ?? [])];
        if (original.index < 0 || original.index >= items.length) {
            return;
        }

        items[original.index] = normalizePaymentItem(edited.item);
        updateValue({items});
    };

    const handleDeleteItem = (row: PaymentItemRow) => {
        const items = [...(currentValue.items ?? [])];
        if (row.index < 0 || row.index >= items.length) {
            return;
        }

        items.splice(row.index, 1);
        updateValue({items});
    };

    const errorText = [
        errors?.join(' '),
        providersError,
    ]
        .filter((part) => part != null && part.length > 0)
        .join(' ');

    return (
        <Box>
            <Typography variant="subtitle2">
                {element.label}{element.required ? ' *' : ''}
            </Typography>

            <Grid
                container
                spacing={2}
                sx={{mt: 0.75}}
            >
                <Grid size={{xs: 12, md: 6}}>
                    <SelectFieldComponent
                        label="Zahlungsdienstleister"
                        value={currentValue.paymentProviderKey}
                        onChange={(providerKey) => updateValue({paymentProviderKey: providerKey})}
                        options={paymentProviderOptions}
                        required={true}
                        disabled={isDisabled || isFieldBusy}
                        emptyStatePlaceholder="Keine Zahlungsdienstleister vorhanden"
                    />
                </Grid>

                <Grid size={{xs: 12, md: 6}}>
                    <TextFieldComponent
                        label="Verwendungszweck"
                        value={currentValue.purpose}
                        onChange={(purpose) => updateValue({purpose})}
                        required={true}
                        disabled={isDisabled || isFieldBusy}
                        hint="Erscheint bei der zahlenden Person auf der Abrechnung."
                    />
                </Grid>

                <Grid size={{xs: 12}}>
                    <TextFieldComponent
                        label="Beschreibung"
                        value={currentValue.description}
                        onChange={(description) => updateValue({description})}
                        required={true}
                        disabled={isDisabled || isFieldBusy}
                        multiline
                        rows={2}
                        hint="Beschreibung der Zahlung für die antragstellende Person."
                    />
                </Grid>
            </Grid>

            <Box sx={{mt: 3.5}}>
                <Typography variant="body1">
                    Antragsteller:in
                </Typography>
                <Typography
                    variant="caption"
                    color="textDisabled"
                >
                    Optionale Zuordnung von Formularwerten zu Zahlungsdaten.
                </Typography>

                <CheckboxFieldComponent
                    label="Antragsteller:in zuordnen"
                    value={currentValue.mapRequestor ?? false}
                    onChange={(mapRequestor) => updateValue({
                        mapRequestor,
                        requestorMapping: mapRequestor ? currentValue.requestorMapping ?? EmptyRequestorMapping : null,
                    })}
                    variant="switch"
                    disabled={isDisabled || isFieldBusy}
                    sx={{mt: 1.5, mb: 0}}
                />

                {
                    currentValue.mapRequestor === true &&
                    <RequestorMappingEditor
                        value={currentValue.requestorMapping ?? EmptyRequestorMapping}
                        onChange={updateRequestorMapping}
                        disabled={isDisabled || isFieldBusy}
                    />
                }
            </Box>

            <Box sx={{mt: 3.5}}>
                <Stack
                    direction="row"
                    spacing={2}
                    alignItems="center"
                    justifyContent="space-between"
                >
                    <Typography variant="body1">
                        Zahlungsposten
                    </Typography>

                    <Button
                        variant="outlined"
                        size="small"
                        startIcon={<Add/>}
                        disabled={isDisabled || isFieldBusy}
                        onClick={handleAddItem}
                    >
                        Hinzufügen
                    </Button>
                </Stack>

                {
                    itemRows.length === 0 &&
                    <EmptyItemsState hasError={errors != null}/>
                }

                {
                    itemRows.length > 0 &&
                    <Box sx={{mt: 0.75}}>
                        <DialogList
                            dialogTitle="Zahlungsposten bearbeiten"
                            dialogViewTitle="Zahlungsposten ansehen"
                            getId={(row) => row.index.toString()}
                            items={itemRows}
                            title={(row) => getPaymentItemTitle(row.item)}
                            subTitle={(row) => getPaymentItemSubtitle(row.item, isDisabled || isFieldBusy)}
                            dialogContentComponent={ItemDialogContent}
                            onDialogSave={handleItemChanged}
                            onDelete={handleDeleteItem}
                            disabled={isDisabled || isFieldBusy}
                        />
                    </Box>
                }
            </Box>

            {
                errorText.length > 0 &&
                <FormHelperText
                    error
                    sx={{
                        mx: 1.75,
                        mt: 0.75,
                    }}
                >
                    {errorText}
                </FormHelperText>
            }
        </Box>
    );
}

function RequestorMappingEditor(props: {
    value: PaymentConfigElementValueRequestorMapping;
    onChange: (field: keyof PaymentConfigElementValueRequestorMapping, value: string | null) => void;
    disabled: boolean;
}) {
    const {
        value,
        onChange,
        disabled,
    } = props;

    return (
        <Grid
            container
            spacing={2}
            sx={{mt: 0.5}}
        >
            <RequestorMappingField
                label="Nachname"
                value={value.lastNameDestinationKey}
                onChange={(next) => onChange('lastNameDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Vorname"
                value={value.firstNameDestinationKey}
                onChange={(next) => onChange('firstNameDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Geschlecht"
                value={value.genderDestinationKey}
                onChange={(next) => onChange('genderDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Ist Organisation"
                value={value.isOrganizationDestinationKey}
                onChange={(next) => onChange('isOrganizationDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Organisationsname"
                value={value.organizationNameDestinationKey}
                onChange={(next) => onChange('organizationNameDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Straße"
                value={value.streeDestinationKey}
                onChange={(next) => onChange('streeDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Hausnummer"
                value={value.houseNumberDestinationKey}
                onChange={(next) => onChange('houseNumberDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Adresszusatz"
                value={value.addressLineDestinationKey}
                onChange={(next) => onChange('addressLineDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Postleitzahl"
                value={value.postalCodeDestinationKey}
                onChange={(next) => onChange('postalCodeDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Ort"
                value={value.cityDestinationKey}
                onChange={(next) => onChange('cityDestinationKey', next)}
                disabled={disabled}
            />
            <RequestorMappingField
                label="Land"
                value={value.countryDestinationKey}
                onChange={(next) => onChange('countryDestinationKey', next)}
                disabled={disabled}
            />
        </Grid>
    );
}

function RequestorMappingField(props: {
    label: string;
    value: string | null;
    onChange: (value: string | null) => void;
    disabled: boolean;
}) {
    return (
        <Grid size={{xs: 12, md: 6}}>
            <ProcessDataKeyInputComponent
                label={props.label}
                value={props.value}
                onChange={props.onChange}
                disabled={props.disabled}
            />
        </Grid>
    );
}

function wrapPaymentConfigItem(rootElement: AnyElement): DialogListPropsDialogContentComponent<PaymentItemRow> {
    return (props: {
        item: PaymentItemRow,
        onChange: (item: PaymentItemRow) => void,
        disabled?: boolean
    }) => (
        <PaymentConfigItemEditor
            item={props.item.item}
            onChange={(item) => props.onChange({
                ...props.item,
                item,
            })}
            rootElement={rootElement}
            disabled={props.disabled ?? false}
        />
    );
}

function PaymentConfigItemEditor(props: {
    item: PaymentConfigElementValueItem;
    onChange: (item: PaymentConfigElementValueItem) => void;
    rootElement: AnyElement;
    disabled: boolean;
}) {
    const {
        item,
        onChange,
        rootElement,
        disabled,
    } = props;

    return (
        <Stack
            spacing={3.5}
            sx={{pt: 1}}
        >
            <Grid
                container
                spacing={2}
            >
                <Grid size={{xs: 12, md: 6}}>
                    <TextFieldComponent
                        label="Beschreibung"
                        value={item.description}
                        onChange={(description) => onChange({...item, description})}
                        required={true}
                        disabled={disabled}
                        muiPassTroughProps={{margin: 'none'}}
                    />
                </Grid>

                <Grid size={{xs: 12, md: 6}}>
                    <TextFieldComponent
                        label="Referenz"
                        value={item.reference}
                        onChange={(reference) => onChange({...item, reference})}
                        required={true}
                        disabled={disabled}
                        muiPassTroughProps={{margin: 'none'}}
                    />
                </Grid>

                <Grid size={{xs: 12, md: 6}}>
                    <SelectFieldComponent
                        label="Kennung"
                        value={item.idType ?? PaymentConfigElementValueItemIdType.AutoGeneratedUUID}
                        onChange={(idType) => onChange({
                            ...item,
                            idType,
                            predefinedId: idType === PaymentConfigElementValueItemIdType.Predefined ? item.predefinedId : null,
                        })}
                        options={IdTypeOptions}
                        disabled={disabled}
                        required={true}
                    />
                </Grid>

                {
                    item.idType === PaymentConfigElementValueItemIdType.Predefined &&
                    <Grid size={{xs: 12, md: 6}}>
                        <TextFieldComponent
                            label="Feste Kennung"
                            value={item.predefinedId}
                            onChange={(predefinedId) => onChange({...item, predefinedId})}
                            required={true}
                            disabled={disabled}
                        />
                    </Grid>
                }
            </Grid>

            <Box>
                <ElementEditorSectionHeader
                    title="Betrag"
                    variant="h5"
                    disableMarginTop
                />

                <Grid
                    container
                    spacing={2}
                    sx={{mt: 0.5}}
                >
                    <Grid size={{xs: 12, md: 6}}>
                        <SelectFieldComponent
                            label="Betrag"
                            value={item.costType ?? PaymentConfigElementValueItemCostType.FixedCosts}
                            onChange={(costType) => onChange({
                                ...item,
                                costType,
                                fixedCosts: costType === PaymentConfigElementValueItemCostType.FixedCosts ? item.fixedCosts : null,
                            })}
                            options={CostTypeOptions}
                            disabled={disabled}
                            required={true}
                        />
                    </Grid>

                    {
                        (item.costType ?? PaymentConfigElementValueItemCostType.FixedCosts) === PaymentConfigElementValueItemCostType.FixedCosts &&
                        <Grid size={{xs: 12, md: 6}}>
                            <NumberFieldComponent
                                label="Einzelpreis (netto)"
                                value={item.fixedCosts}
                                onChange={(fixedCosts) => onChange({...item, fixedCosts})}
                                decimalPlaces={2}
                                minValue={0}
                                suffix="Euro"
                                required={true}
                                disabled={disabled}
                            />
                        </Grid>
                    }

                    {
                        item.costType === PaymentConfigElementValueItemCostType.VariableCosts &&
                        <Grid size={{xs: 12, md: 6}}>
                            <SelectFieldComponent
                                label="Berechnung"
                                value={item.variableCostsCalculationType}
                                onChange={(variableCostsCalculationType) => onChange({
                                    ...item,
                                    variableCostsCalculationType,
                                })}
                                options={CalculationTypeOptions}
                                disabled={disabled}
                                required={true}
                            />
                        </Grid>
                    }
                </Grid>

                {
                    item.costType === PaymentConfigElementValueItemCostType.VariableCosts &&
                    <Box
                        sx={{
                            mt: 2,
                        }}
                    >
                        <PaymentValueCalculationEditor
                            label="Betrag berechnen"
                            rootElement={rootElement}
                            calculationType={item.variableCostsCalculationType}
                            noCodeCalculation={item.variableCostsNoCodeCalculation}
                            lowCodeCalculation={item.variableCostsLowCodeCalculation}
                            onNoCodeChange={(variableCostsNoCodeCalculation) => onChange({
                                ...item,
                                variableCostsNoCodeCalculation,
                            })}
                            onLowCodeChange={(variableCostsLowCodeCalculation) => onChange({
                                ...item,
                                variableCostsLowCodeCalculation,
                            })}
                            disabled={disabled}
                        />
                    </Box>
                }
            </Box>

            <Box>
                <ElementEditorSectionHeader
                    title="Menge"
                    variant="h5"
                    disableMarginTop
                />

                <Grid
                    container
                    spacing={2}
                    sx={{mt: 0.5}}
                >
                    <Grid size={{xs: 12, md: 6}}>
                        <SelectFieldComponent
                            label="Menge"
                            value={item.quantityType ?? PaymentConfigElementValueItemQuantityType.FixedQuantity}
                            onChange={(quantityType) => onChange({
                                ...item,
                                quantityType,
                                fixedQuantity: quantityType === PaymentConfigElementValueItemQuantityType.FixedQuantity ? item.fixedQuantity : null,
                            })}
                            options={QuantityTypeOptions}
                            disabled={disabled}
                            required={true}
                        />
                    </Grid>

                    {
                        (item.quantityType ?? PaymentConfigElementValueItemQuantityType.FixedQuantity) === PaymentConfigElementValueItemQuantityType.FixedQuantity &&
                        <Grid size={{xs: 12, md: 6}}>
                            <NumberFieldComponent
                                label="Menge"
                                value={item.fixedQuantity}
                                onChange={(fixedQuantity) => onChange({
                                    ...item,
                                    fixedQuantity: fixedQuantity == null ? null : Math.round(fixedQuantity),
                                })}
                                minValue={0}
                                decimalPlaces={0}
                                required={true}
                                disabled={disabled}
                            />
                        </Grid>
                    }

                    {
                        item.quantityType === PaymentConfigElementValueItemQuantityType.VariableQuantity &&
                        <Grid size={{xs: 12, md: 6}}>
                            <SelectFieldComponent
                                label="Berechnung"
                                value={item.variableQuantityCalculationType}
                                onChange={(variableQuantityCalculationType) => onChange({
                                    ...item,
                                    variableQuantityCalculationType,
                                })}
                                options={CalculationTypeOptions}
                                disabled={disabled}
                                required={true}
                            />
                        </Grid>
                    }
                </Grid>

                {
                    item.quantityType === PaymentConfigElementValueItemQuantityType.VariableQuantity &&
                    <Box
                        sx={{
                            mt: 2,
                        }}
                    >
                        <PaymentValueCalculationEditor
                            label="Menge berechnen"
                            rootElement={rootElement}
                            calculationType={item.variableQuantityCalculationType}
                            noCodeCalculation={item.variableQuantityNoCodeCalculation}
                            lowCodeCalculation={item.variableQuantityLowCodeCalculation}
                            onNoCodeChange={(variableQuantityNoCodeCalculation) => onChange({
                                ...item,
                                variableQuantityNoCodeCalculation,
                            })}
                            onLowCodeChange={(variableQuantityLowCodeCalculation) => onChange({
                                ...item,
                                variableQuantityLowCodeCalculation,
                            })}
                            disabled={disabled}
                        />
                    </Box>
                }
            </Box>

            <Box>
                <ElementEditorSectionHeader
                    title="Weitere Daten"
                    variant="h5"
                    disableMarginTop
                />

                <Grid
                    container
                    spacing={2}
                    sx={{mt: 0.5}}
                >
                    <Grid size={{xs: 12, md: 6}}>
                        <NumberFieldComponent
                            label="Steuersatz"
                            value={item.fixedTaxRate}
                            onChange={(taxRate) => onChange({...item, fixedTaxRate: taxRate})}
                            decimalPlaces={2}
                            minValue={0}
                            maxValue={100}
                            suffix="%"
                            disabled={disabled}
                        />
                    </Grid>
                </Grid>

                <AdditionalBookingDataEditor
                    value={item.additionalBookingData}
                    onChange={(additionalBookingData) => onChange({...item, additionalBookingData})}
                    disabled={disabled}
                />
            </Box>
        </Stack>
    );
}

function PaymentValueCalculationEditor(props: {
    label: string;
    rootElement: AnyElement;
    calculationType: PaymentConfigElementValueItemVariableValueCalculationType | null;
    noCodeCalculation: NoCodeOperand | null;
    lowCodeCalculation: JavascriptCode | null;
    onNoCodeChange: (value: NoCodeOperand | null) => void;
    onLowCodeChange: (value: JavascriptCode | null) => void;
    disabled: boolean;
}) {
    const calculationType = props.calculationType ?? PaymentConfigElementValueItemVariableValueCalculationType.NoCode;

    return (
        <>
            {
                calculationType === PaymentConfigElementValueItemVariableValueCalculationType.NoCode &&
                <NoCodeInputFieldComponent
                    rootElement={props.rootElement}
                    label={props.label}
                    value={props.noCodeCalculation == null ? null : {noCode: props.noCodeCalculation}}
                    desiredReturnType={NoCodeDataType.Number}
                    onChange={(value) => props.onNoCodeChange(value?.noCode ?? null)}
                    disabled={props.disabled}
                    disablePopoutModeWhenFormLayoutChild={true}
                />
            }

            {
                calculationType === PaymentConfigElementValueItemVariableValueCalculationType.LowCode &&
                <CodeInputFieldComponent
                    label={props.label}
                    value={props.lowCodeCalculation?.code}
                    onChange={(code) => props.onLowCodeChange(code == null ? null : {code})}
                    language="javascript"
                    height="220px"
                    disabled={props.disabled}
                />
            }
        </>
    );
}

function AdditionalBookingDataEditor(props: {
    value: Record<string, string> | null;
    onChange: (value: Record<string, string> | null) => void;
    disabled: boolean;
}) {
    const rows = Object.entries(props.value ?? {});

    const updateRows = (nextRows: Array<[string, string]>) => {
        const nextValue = Object.fromEntries(nextRows.filter(([key]) => !isStringNullOrEmpty(key)));
        props.onChange(Object.keys(nextValue).length === 0 ? null : nextValue);
    };

    return (
        <Box sx={{mt: 2}}>
            <Stack
                direction="row"
                spacing={2}
                alignItems="center"
                justifyContent="space-between"
                sx={{mb: rows.length === 0 ? 0 : 1.5}}
            >
                <Typography variant="subtitle2">
                    Buchungsdaten
                </Typography>

                <Button
                    variant="outlined"
                    size="small"
                    startIcon={<Add/>}
                    disabled={props.disabled}
                    onClick={() => updateRows([...rows, [`schluessel${rows.length + 1}`, '']])}
                >
                    Hinzufügen
                </Button>
            </Stack>

            <Stack spacing={1.5}>
                {
                    rows.map(([key, value], index) => (
                        <Grid
                            key={index}
                            container
                            spacing={1.5}
                            alignItems="flex-start"
                        >
                            <Grid size={{xs: 12, md: 5}}>
                                <TextFieldComponent
                                    label="Schlüssel"
                                    value={key}
                                    onChange={(nextKey) => {
                                        const nextRows = [...rows];
                                        nextRows[index] = [nextKey ?? '', value];
                                        updateRows(nextRows);
                                    }}
                                    disabled={props.disabled}
                                    muiPassTroughProps={{margin: 'none'}}
                                />
                            </Grid>

                            <Grid size={{xs: 12, md: 5}}>
                                <TextFieldComponent
                                    label="Wert"
                                    value={value}
                                    onChange={(nextValue) => {
                                        const nextRows = [...rows];
                                        nextRows[index] = [key, nextValue ?? ''];
                                        updateRows(nextRows);
                                    }}
                                    disabled={props.disabled}
                                    muiPassTroughProps={{margin: 'none'}}
                                />
                            </Grid>

                            <Grid size={{xs: 12, md: 2}}>
                                <Button
                                    variant="outlined"
                                    size="small"
                                    startIcon={<Delete/>}
                                    disabled={props.disabled}
                                    onClick={() => updateRows(rows.filter((_, rowIndex) => rowIndex !== index))}
                                    sx={{mt: {xs: 0, md: 1}}}
                                >
                                    Entfernen
                                </Button>
                            </Grid>
                        </Grid>
                    ))
                }
            </Stack>
        </Box>
    );
}

function EmptyItemsState(props: { hasError: boolean }) {
    return (
        <Box
            sx={(theme) => ({
                px: 1.5,
                py: 1.25,
                mt: 0.75,
                minHeight: 56,
                display: 'flex',
                alignItems: 'center',
                borderRadius: 1,
                border: props.hasError ? '1px solid' : '1px dashed',
                borderColor: props.hasError ? theme.palette.error.main : alpha(theme.palette.text.primary, 0.18),
            })}
        >
            <Stack
                direction="row"
                spacing={1}
                alignItems="center"
            >
                <Receipt
                    sx={{
                        flexShrink: 0,
                        fontSize: 20,
                        color: 'text.secondary',
                    }}
                />
                <Typography
                    variant="body2"
                    color="text.secondary"
                    sx={{minWidth: 0}}
                >
                    Keine Zahlungsposten vorhanden.
                </Typography>
            </Stack>
        </Box>
    );
}

function createPaymentItem(): PaymentConfigElementValueItem {
    return {
        idType: PaymentConfigElementValueItemIdType.AutoGeneratedUUID,
        predefinedId: null,
        description: null,
        reference: null,
        costType: PaymentConfigElementValueItemCostType.FixedCosts,
        fixedCosts: 0,
        variableCostsCalculationType: PaymentConfigElementValueItemVariableValueCalculationType.NoCode,
        variableCostsNoCodeCalculation: null,
        variableCostsLowCodeCalculation: null,
        quantityType: PaymentConfigElementValueItemQuantityType.FixedQuantity,
        fixedQuantity: 1,
        variableQuantityCalculationType: PaymentConfigElementValueItemVariableValueCalculationType.NoCode,
        variableQuantityNoCodeCalculation: null,
        variableQuantityLowCodeCalculation: null,
        fixedTaxRate: 0,
        additionalBookingData: null,
    };
}

function normalizePaymentItem(item: PaymentConfigElementValueItem): PaymentConfigElementValueItem {
    return {
        ...createPaymentItem(),
        ...item,
        idType: item.idType ?? PaymentConfigElementValueItemIdType.AutoGeneratedUUID,
        costType: item.costType ?? PaymentConfigElementValueItemCostType.FixedCosts,
        quantityType: item.quantityType ?? PaymentConfigElementValueItemQuantityType.FixedQuantity,
        variableCostsCalculationType: item.variableCostsCalculationType ?? PaymentConfigElementValueItemVariableValueCalculationType.NoCode,
        variableQuantityCalculationType: item.variableQuantityCalculationType ?? PaymentConfigElementValueItemVariableValueCalculationType.NoCode,
    };
}

function normalizePaymentConfigValue(value: PaymentConfigElementValue | null | undefined): PaymentConfigElementValue {
    return {
        ...EmptyPaymentConfigValue,
        ...value,
        mapRequestor: value?.mapRequestor ?? false,
        requestorMapping: value?.requestorMapping ?? null,
        items: value?.items ?? [],
    };
}

function isPaymentConfigValueEmpty(value: PaymentConfigElementValue): boolean {
    return value.paymentProviderKey == null &&
        isStringNullOrEmpty(value.purpose) &&
        isStringNullOrEmpty(value.description) &&
        value.mapRequestor !== true &&
        (value.items?.length ?? 0) === 0;
}

function getPaymentItemTitle(item: PaymentConfigElementValueItem): string {
    if (!isStringNullOrEmpty(item.description)) {
        return item.description!;
    }

    if (!isStringNullOrEmpty(item.reference)) {
        return item.reference!;
    }

    return 'Unbenannter Zahlungsposten';
}

function getPaymentItemSubtitle(item: PaymentConfigElementValueItem, isReadonly: boolean): string {
    const cost = item.costType === PaymentConfigElementValueItemCostType.VariableCosts ?
        'Berechneter Betrag' :
        `${item.fixedCosts ?? 0} Euro`;
    const quantity = item.quantityType === PaymentConfigElementValueItemQuantityType.VariableQuantity ?
        'Berechnete Menge' :
        `${item.fixedQuantity ?? 0}x`;

    return [
        cost,
        quantity,
        item.fixedTaxRate != null ? `${item.fixedTaxRate}% Steuer` : undefined,
        isReadonly ? 'Zum Anzeigen öffnen' : undefined,
    ]
        .filter((part) => part != null)
        .join(' · ');
}
