version: '3.1'

services:

  database:
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: 'gover'
      POSTGRES_USER: 'gover'
      POSTGRES_DB: 'gover'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  clamav:
    image: 'clamav/clamav-debian'
    restart: 'always'
    ports:
      - '3310:3310'

  redis:
    image: 'redis:7.2.4'
    restart: 'always'
    ports:
      - '6379:6379'

  puppet:
    image: ghcr.io/aivot-digital/puppet-pdf:1.3.3
    restart: 'always'
    ports:
      - '4000:3000'

  minio:
    image: minio/minio
    restart: 'always'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'adminpassword'
    ports:
      - '9000:9000'
      - '9001:9001'

  keycloak:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins:26.0.2.0
    restart: 'always'
    command: [ 'start-dev', '--http-port=8081' ]
    environment:
      KC_PROXY: 'edge'
      KC_HOSTNAME: 'localhost'
      KC_HOSTNAME_PORT: '8888'
      KC_HOSTNAME_PATH: '/idp'
      KC_HTTP_RELATIVE_PATH: '/idp'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    ports:
      - '8081:8081'

  fakesmtp:
    image: ghusta/fakesmtp:2.0
    restart: 'always'
    ports:
      - '2525:25'
    volumes:
      - './fakesmtp:/var/mail'

  nginx:
    image: nginx:1.25-alpine
    restart: 'always'
    volumes:
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8888:8888'
