version: '3.1'

services:

  gover-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: gover
      POSTGRES_USER: gover
      POSTGRES_DB: gover
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  gover:
    image: aivot-digital/gover
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gover-database
    restart: always
    volumes:
      - ./media:/app/media
      - ./config:/app/config:ro
    ports:
      - "8080:8080"
