version: '3.1'

services:

  database:
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: 'gover'
      POSTGRES_USER: 'gover'
      POSTGRES_DB: 'gover'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  clamav:
    image: 'clamav/clamav'
    restart: 'always'
    ports:
      - '3310:3310'

  influxdb:
    image: influxdb
    restart: 'always'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'gover'
      DOCKER_INFLUXDB_INIT_PASSWORD: 'gover-password'
      DOCKER_INFLUXDB_INIT_ORG: 'gover'
      DOCKER_INFLUXDB_INIT_BUCKET: 'gover'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'gover'
    ports:
      - '8086:8086'
