upstream backend {
  server localhost:8080;
}

server {
  listen 80      default_server;
  listen [::]:80 default_server;

  location /admin {
    alias     /var/www/admin/html/;
    try_files $uri $uri/ /index.html;
  }

  location ^~/api/ {
    proxy_pass       http://backend/;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    root      /var/www/app/html;
    try_files $uri $uri/ /index.html;
  }
}