insert into themes (id,
                    name,
                    main,
                    main_dark,
                    accent,
                    success,
                    info,
                    warning,
                    error)
values (1,
        'Entenhausen',
        '#004777',
        '#00253D',
        '#A30000',
        '#28a745',
        '#17a2b8',
        '#ffc107',
        '#dc3545'),
       (2,
        'Tanzigel',
        '#F34213',
        '#9B2808',
        '#B09D1C',
        '#28a745',
        '#17a2b8',
        '#ffc107',
        '#dc3545')
on conflict (id) do update
    set name      = excluded.name,
        main      = excluded.main,
        main_dark = excluded.main_dark,
        accent    = excluded.accent,
        success   = excluded.success,
        info      = excluded.info,
        warning   = excluded.warning,
        error     = excluded.error;

insert into departments (id,
                         name,
                         address,
                         imprint,
                         common_privacy,
                         common_accessibility,
                         technical_support_address,
                         special_support_address,
                         department_mail,
                         theme_id,
                         technical_support_phone,
                         technical_support_info,
                         special_support_phone,
                         special_support_info,
                         additional_info,
                         parent_department_id,
                         created,
                         updated)
values (1,
        'Stadtverwaltung Entenhausen',
        E'Marktplatz 1\n12345 Entenhausen',
        'Impressum der Stadtverwaltung Entenhausen',
        'Datenschutzhinweis der Stadtverwaltung Entenhausen',
        'Barrierefreiheitshinweis der Stadtverwaltung Entenhausen',
        'it@entenhausen.de',
        'info@entenhausen.de',
        null,
        1,
        '+49 123 4567890',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 123 0987654',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Zusätzliche Informationen zur Stadtverwaltung Entenhausen',
        null,
        now(),
        now()),
       (2,
        'IT',
        null,
        null,
        null,
        null,
        null,
        'it@entenhausen.de',
        null,
        null,
        null,
        null,
        '+49 123 0987654',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        'Bitte wenden Sie sich bei IT-Problemen an diese Abteilung.',
        1,
        now(),
        now()),
       (3,
        'Finanzamt',
        E'An der Goldgrube 4\n12345 Entenhausen',
        null,
        null,
        null,
        null,
        'finanzen@entenhausen.de',
        null,
        null,
        null,
        null,
        '+49 321 1234567',
        E'Mo. bis Fr. 09:00 Uhr bis 12:00 Uhr\nDo. 14:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (4,
        'Sozialamt',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (5,
        'Kita Tanzigel',
        E'Tanzigelweg 5\n12345 Entenhausen',
        null,
        null,
        null,
        null,
        'mail@kita-tanzigel.de',
        null,
        2,
        null,
        null,
        '01701234567',
        'Mo. bis Fr. 06:00 Uhr bis 16:00 Uhr',
        null,
        4,
        now(),
        now())
on conflict (id) do update
    set name                      = excluded.name,
        address                   = excluded.address,
        imprint                   = excluded.imprint,
        common_privacy            = excluded.common_privacy,
        common_accessibility      = excluded.common_accessibility,
        technical_support_address = excluded.technical_support_address,
        special_support_address   = excluded.special_support_address,
        department_mail           = excluded.department_mail,
        theme_id                  = excluded.theme_id,
        technical_support_phone   = excluded.technical_support_phone,
        technical_support_info    = excluded.technical_support_info,
        special_support_phone     = excluded.special_support_phone,
        special_support_info      = excluded.special_support_info,
        additional_info           = excluded.additional_info,
        parent_department_id      = excluded.parent_department_id,
        updated                   = now();

insert into teams (id,
                   name)
values (1,
        'Entwicklungshelfer'),
       (2,
        'Prüfteam')
on conflict (id) do update
    set name = excluded.name;

insert into system_configs (key,
                            value)
values ('SystemTheme', '1')
on conflict (key) do update
    set value = excluded.value;

insert into forms (id,
                   developing_department_id,
                   slug,
                   internal_title,
                   published_version,
                   drafted_version,
                   version_count,
                   updated,
                   created)
values (1,
        2,
        'it-support-anfrage',
        'IT-Support Anfrage',
        null,
        null,
        0,
        now(),
        now()),
       (2,
        2,
        'anmeldung-kita-tanzigel',
        'Anmeldung Kita Tanzigel',
        null,
        null,
        0,
        now(),
        now()),
       (3,
        3,
        'antrag-auf-steuerstundung',
        'Antrag auf Steuerstundung',
        null,
        null,
        0,
        now(),
        now())
on conflict (id) do update
    set developing_department_id = excluded.developing_department_id,
        slug                     = excluded.slug,
        internal_title           = excluded.internal_title,
        published_version        = excluded.published_version,
        drafted_version          = excluded.drafted_version,
        version_count            = excluded.version_count,
        updated                  = now();

insert into resource_access_controls (id,
                                      source_department_id,
                                      source_team_id,
                                      target_form_id,
                                      form_permission_read,
                                      form_permission_edit,
                                      form_permission_annotate)
values (1,
        5,
        null,
        2,
        true,
        false,
        true),
       (2,
        null,
        1,
        3,
        true,
        true,
        false),
       (3,
        null,
        2,
        3,
        true,
        false,
        false)
on conflict (id) do update
    set source_department_id     = excluded.source_department_id,
        target_form_id           = excluded.target_form_id,
        form_permission_read     = excluded.form_permission_read,
        form_permission_annotate = excluded.form_permission_annotate;

insert into data_object_schemas (key,
                                 name,
                                 description,
                                 id_gen,
                                 schema,
                                 created,
                                 updated,
                                 display_fields)
values ('kita_kinder',
        'Kita Kinder',
        'Kinder in der Kita',
        '__SERIAL__',
        '{
            "id": "kind",
            "type": 3,
            "weight": 12.0,
            "children": [
                {
                    "id": "vorname",
                    "type": 15,
                    "label": "Vorname",
                    "weight": 6.0,
                    "disabled": false,
                    "required": true,
                    "technical": false,
                    "isMultiline": false
                },
                {
                    "id": "nachname",
                    "type": 15,
                    "label": "Nachname",
                    "weight": 6.0,
                    "disabled": false,
                    "required": true,
                    "technical": false,
                    "isMultiline": false
                },
                {
                    "id": "geburtstag",
                    "mode": "day",
                    "type": 5,
                    "label": "Geburtstag",
                    "weight": 12.0,
                    "disabled": false,
                    "required": true,
                    "technical": false
                }
            ]
        }',
        now(),
        now(),
        '{vorname,nachname}')
on conflict (key) do update
    set name           = excluded.name,
        description    = excluded.description,
        id_gen         = excluded.id_gen,
        schema         = excluded.schema,
        updated        = now(),
        display_fields = excluded.display_fields;

insert into data_object_items (schema_key,
                               id,
                               data,
                               created,
                               updated,
                               deleted)
values ('kita_kinder',
        '1',
        '{
            "vorname": "Erwin",
            "nachname": "Erpel",
            "geburtstag": "1997-12-11T23:06:32Z"
        }',
        now(),
        now(),
        null),
       ('kita_kinder',
        '2',
        '{
            "vorname": "Edna",
            "nachname": "Quack",
            "geburtstag": "1998-05-08T23:06:32Z"
        }',
        now(),
        now(),
        null)
on conflict (schema_key,
    id) do update
    set data    = excluded.data,
        updated = now(),
        deleted = excluded.deleted;
