-- create example departments
insert into departments (id,
                         name,
                         address,
                         imprint,
                         common_privacy,
                         common_accessibility,
                         technical_support_address,
                         special_support_address,
                         department_mail,
                         theme_id,
                         technical_support_phone,
                         technical_support_info,
                         special_support_phone,
                         special_support_info,
                         additional_info,
                         parent_department_id,
                         created,
                         updated)
values (1,
        'Verwaltungsstelle soziale Hilfen',
        E'Malzstraße 1a\n12345 Bad Musterstadt',
        'Impressum der Verwaltungsstelle soziale Hilfen',
        'Datenschutzhinweis der Verwaltungsstelle soziale Hilfen',
        'Barrierefreiheitshinweis der Verwaltungsstelle soziale Hilfen',
        'it@example.com',
        'info@example',
        null,
        1,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zur Verwaltungsstelle soziale Hilfen finden Sie auf der <a href="https://example.com">Webseite</a>.',
        null,
        now(),
        now()),
       (2,
        'IT',
        null,
        null,
        null,
        null,
        null,
        'it@example.com',
        null,
        null,
        null,
        null,
        '+49 2405 404-2',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (3,
        'Verhandler VIII',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (4,
        'Verhandler IX',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (5,
        'Prüfteam',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (6,
        'Kreis Flön',
        E'Marktplatz 1\n12345 Flön',
        'Impressum des Kreises Flön',
        'Datenschutzhinweis des Kreises Flön',
        'Barrierefreiheitshinweis des Kreises Flön',
        'it@example.com',
        'info@example.com',
        null,
        2,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zum Kreis Flön finden Sie auf der <a href="https://example.com">Webseite</a>.',
        null,
        now(),
        now()),
       (7,
        'Finanzamt Flön',
        E'Goldweg 2\n12345 Flön',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        6,
        now(),
        now()),
       (8,
        'Kreis Westbringstein',
        E'Am Meer 4\n54321 Oideen',
        'Impressum des Kreises Westbringstein',
        'Datenschutzhinweis des Kreises Westbringstein',
        'Barrierefreiheitshinweis des Kreises Westbringstein',
        'it@example.com',
        'info@example.com',
        null,
        3,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zum Kreis Westbringstein finden Sie auf der <a href="https://example.com">Webseite</a>.',
        null,
        now(),
        now()),
       (9,
        'Sozialamt',
        E'Beerenweg 5\n54321 Oideen',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        8,
        now(),
        now()),
       (10,
        'Kreisfreie Stadt Altkirchen',
        E'Im Einöd 3\n32154 Altkirchen',
        'Impressum der Kreisfreien Stadt Altkirchen',
        'Datenschutzhinweis der Kreisfreien Stadt Altkirchen',
        'Barrierefreiheitshinweis der Kreisfreien Stadt Altkirchen',
        'it@example.com',
        'info@example.com',
        null,
        4,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zur Kreisfreien Stadt Altkirchen finden Sie auf der <a href="https://example.com">Webseite</a>.',
        null,
        now(),
        now())
on conflict (id) do update
    set name                      = excluded.name,
        address                   = excluded.address,
        imprint                   = excluded.imprint,
        common_privacy            = excluded.common_privacy,
        common_accessibility      = excluded.common_accessibility,
        technical_support_address = excluded.technical_support_address,
        special_support_address   = excluded.special_support_address,
        department_mail           = excluded.department_mail,
        theme_id                  = excluded.theme_id,
        technical_support_phone   = excluded.technical_support_phone,
        technical_support_info    = excluded.technical_support_info,
        special_support_phone     = excluded.special_support_phone,
        special_support_info      = excluded.special_support_info,
        additional_info           = excluded.additional_info,
        parent_department_id      = excluded.parent_department_id,
        updated                   = now();

-- fix id sequence for departments
select setval('departments_id_seq',
              (select max(id) from departments));

-- assign the default vendor name
insert into system_configs (key,
                            value)
values ('ProviderName', 'Verwaltungsstelle für soziale Hilfen in Musterland')
on conflict (key) do update
    set value = excluded.value;