# -------------------------- Usage --------------------------
# Start this with: docker compose -f ./docker-compose.yml up -d
# -----------------------------------------------------------
name: gover_dev_environment

services:

  gover_database:
    image: postgres:16.10-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: gover
      POSTGRES_USER: gover
      POSTGRES_DB: gover
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - gover_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  antivirus:
    image: clamav/clamav-debian:1.5.1
    restart: unless-stopped
    ports:
      - "3310:3310"

  cache:
    image: redis:8.2.2-alpine3.22
    restart: unless-stopped
    ports:
      - "6379:6379"

  pdf_printer:
    image: gotenberg/gotenberg:8.24.0
    restart: unless-stopped
    network_mode: host
    environment:
      API_PORT: 9191

  s3_object_storage:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  smtp:
    image: axllent/mailpit:v1.27.10
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    ports:
      - "9025:8025"
      - "2025:1025"

  keycloak_database:
    image: postgres:16.10-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins:26.2.4.1
    restart: unless-stopped
    depends_on:
      - keycloak_database
    command: [ 'start-dev' ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: http://localhost:9595/idp
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: false
      KC_HOSTNAME_DEBUG: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: transient-users,update-email,hostname:v2

  keycloak_setup:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins-setup:0.0.5
    restart: on-failure
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      SMTP_HOST: "smtp"
      SMTP_PORT: "1025"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "mail"
      SMTP_FROM_DISPLAY: "Mail Test"
      HOSTNAME: "http://localhost:9595"
      BACKEND_CLIENT_SECRET: "my-super-secret-key"

  message_broker:
    image: rabbitmq:4.1.4-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  reverse_proxy:
    image: caddy:2.10.0-alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "9595:80"

volumes:
  gover_pg_data:
  keycloak_pg_data:
  minio_data:
  mailpit_data:
  rabbitmq_data:
