spring.datasource.url=jdbc:postgresql://localhost:5432/gover
spring.datasource.username=gover
spring.datasource.password=gover

spring.data.rest.basePath=/api

server.error.include-message=always

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mein-super-secret-key
jwt.expiration=604800000

spring.mail.host=<SMTP_HOST>
spring.mail.port=465
spring.mail.username=<SMTP_USERNAME>
spring.mail.password=<SMTP_PASSWORD>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gover.reportMail=<ADMIN_EMAIL_ADDRESS>
