spring.datasource.url=jdbc:postgresql://localhost:5432/gover
spring.datasource.username=gover
spring.datasource.password=gover

spring.data.rest.basePath=/api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=ON_PARAM
server.error.include-exception=true

logging.level.org.springframework.web=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# jwt.secret=${random.value}
jwt.expiration=604800000

spring.mail.host=smtp.aivot.de
spring.mail.port=465
spring.mail.username=gover@aivot.de
spring.mail.password=not-the-real-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gover.fromMail=noreply@aivot.de
gover.reportMail=gover@aivot.de
