spring.datasource.url=jdbc:postgresql://${GOVER_DB_HOST}:${GOVER_DB_PORT}/${GOVER_DB_DATABASE}?stringtype=unspecified
spring.datasource.username=${GOVER_DB_USERNAME}
spring.datasource.password=${GOVER_DB_PASSWORD}

spring.data.rest.basePath=/api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=ON_PARAM
server.error.include-exception=true

management.endpoints.web.base-path=/api/public/actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.health.show-details=when-authorized
management.health.diskspace.enabled=true
management.health.db.enabled=true
management.health.mail.enabled=true

management.metrics.export.influx.uri=http://${GOVER_INFLUX_HOST}:${GOVER_INFLUX_PORT}
management.metrics.export.influx.org=${GOVER_INFLUX_ORG}
management.metrics.export.influx.bucket=${GOVER_INFLUX_BUCKET}
management.metrics.export.influx.token=${GOVER_INFLUX_TOKEN}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.flyway.enabled=true

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.error.whitelabel.enabled=false

spring.mail.host=${GOVER_SMTP_HOST}
spring.mail.port=${GOVER_SMTP_PORT}
spring.mail.username=${GOVER_SMTP_USERNAME}
spring.mail.password=${GOVER_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO

jwt.secret=${GOVER_JWT_SECRET}
jwt.expiration=604800000

clam.host=${GOVER_CLAM_HOST}
clam.port=${GOVER_CLAM_PORT}

gover.fromMail=${GOVER_FROM_MAIL}
gover.reportMail=${GOVER_REPORT_MAIL}
gover.sentryServer=${GOVER_SENTRY_SERVER}
gover.sentryWebApp=${GOVER_SENTRY_WEB_APP}
gover.environment=${GOVER_ENVIRONMENT}
gover.fileExtensions=${GOVER_FILE_EXTENSIONS}
gover.contentTypes=${GOVER_CONTENT_TYPES}
gover.hostname=${GOVER_HOSTNAME}
