name: prosuna

services:
  prosuna_api:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: serve
    depends_on:
      - prosuna_database
      - keycloak
      - clamav
      - redis
      - rabbitmq
      - mailpit
    environment:
      PROSUNA_SERVER_PORT: 9595
      PROSUNA_DB_HOST: prosuna_database
      PROSUNA_DB_PORT: 5432
      PROSUNA_DB_USERNAME: prosuna
      PROSUNA_DB_PASSWORD: ${PROSUNA_DB_PASSWORD}
      PROSUNA_DB_DATABASE: prosuna
      PROSUNA_REDIS_HOST: redis
      PROSUNA_REDIS_PORT: 6379
      PROSUNA_REDIS_DATABASE: 0
      PROSUNA_SMTP_HOST: mailpit
      PROSUNA_SMTP_PORT: 1025
      PROSUNA_SMTP_AUTH: false
      PROSUNA_RABBITMQ_HOST: rabbitmq
      PROSUNA_RABBITMQ_PORT: 5672
      PROSUNA_RABBITMQ_USERNAME: prosuna
      PROSUNA_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PROSUNA_CLAM_HOST: clamav
      PROSUNA_CLAM_PORT: 3310
      PROSUNA_GOTENBERG_HOST: localhost
      PROSUNA_GOTENBERG_PORT: 3000
      PROSUNA_KEYCLOAK_OIDC_HOSTNAME: http://localhost:9595/idp
      PROSUNA_KEYCLOAK_OIDC_INTERNAL_HOSTNAME: http://keycloak:8080
      PROSUNA_KEYCLOAK_OIDC_REALM: staff
      PROSUNA_KEYCLOAK_OIDC_FRONTEND_CLIENT_ID: app
      PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_ID: backend
      PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET: ${PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
      PROSUNA_SECRETS_KEY: ${PROSUNA_SECRETS_KEY}
      PROSUNA_CAPTCHA_KEY: ${PROSUNA_CAPTCHA_KEY}
      PROSUNA_HOSTNAME: http://localhost:9595
      PROSUNA_SUPPORT_URL: https://support.aivot.de
      PROSUNA_TIMEZONE: Europe/Berlin
      PROSUNA_FROM_MAIL: mail@example.com
      PROSUNA_REPORT_MAIL: mail@example.com
      PROSUNA_BOOTSTRAP_ADMIN_MAIL: admin@example.com
    volumes:
      - prosuna_data:/app/data
    networks:
      - prosuna
      - prosuna_keycloak
      - mail
      - proxy

  prosuna_app:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: web
    network_mode: "service:prosuna_api"
    depends_on:
      prosuna_api:
        condition: service_healthy
        restart: true
      gotenberg:
        condition: service_started
        restart: true
    environment:
      PROSUNA_HOSTNAME: http://localhost:9595

  prosuna_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PROSUNA_DB_PASSWORD}
      POSTGRES_USER: prosuna
      POSTGRES_DB: prosuna
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: Europe/Berlin
    volumes:
      - prosuna_database_data:/var/lib/postgresql/data
    networks:
      - prosuna

  keycloak:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins:26.6.4.2
    restart: unless-stopped
    depends_on:
      - keycloak_database
    command: start-dev
    environment:
      KC_HOSTNAME: http://localhost:9595/idp
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_BOOTSTRAP_ADMIN_USERNAME: bootstrap_admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: bootstrap_admin
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_FEATURES: transient-users,update-email,hostname:v2
    networks:
      - keycloak
      - prosuna_keycloak
      - mail
      - proxy

  keycloak_setup:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins-setup:0.0.24
    restart: on-failure
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      HOSTNAME: http://localhost:9595
      KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: bootstrap_admin
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: bootstrap_admin
      KEYCLOAK_DEPLOYMENT_CLIENT_NAME: deployment
      KEYCLOAK_DEPLOYMENT_CLIENT_SECRET: ${KEYCLOAK_DEPLOYMENT_CLIENT_SECRET}
      KEYCLOAK_ADMIN_EMAIL: mail@example.com
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      LOGGING_LEVEL_HTTP: ERROR
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: mail@example.com
      SMTP_FROM_DISPLAY: ProsunaIDP
      BACKEND_CLIENT_SECRET: ${PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
    networks:
      - keycloak

  keycloak_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_database_data:/var/lib/postgresql/data
    networks:
      - keycloak

  clamav:
    image: docker.io/clamav/clamav:1.5-debian
    restart: unless-stopped
    networks:
      - prosuna

  redis:
    image: docker.io/redis:8-alpine
    restart: unless-stopped
    networks:
      - prosuna

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    network_mode: "service:prosuna_api"
    depends_on:
      prosuna_api:
        condition: service_started
        restart: true
    environment:
      CHROMIUM_DENY_PRIVATE_IPS: "true"
      CHROMIUM_DENY_PUBLIC_IPS: "true"
      CHROMIUM_ALLOW_LIST: "^(http://localhost:9595/|file:///tmp/)"

  mailpit:
    image: docker.io/axllent/mailpit:v1.30
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    ports:
      - "9025:8025"
    networks:
      - mail

  rabbitmq:
    image: docker.io/rabbitmq:4-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: prosuna
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - prosuna

  caddy:
    image: docker.io/caddy:2-alpine
    restart: unless-stopped
    depends_on:
      prosuna_api:
        condition: service_healthy
        restart: true
      prosuna_app:
        condition: service_healthy
        restart: true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
    ports:
      - "9595:80"
    networks:
      - proxy


volumes:
  prosuna_data:
  prosuna_database_data:
  keycloak_database_data:
  mailpit_data:
  rabbitmq_data:


networks:
  prosuna:
  keycloak:
  prosuna_keycloak:
  mail:
  proxy:
