import {BaseInputElement} from '../base-input-element';
import {ElementType} from '../../../../data/element-type/element-type';
import {NoCodeOperand} from '../../../functions/no-code-expression';
import {JavascriptCode} from '../../../functions/javascript-code';

export interface PaymentConfigElement extends BaseInputElement<ElementType.PaymentConfigElement> {
}

export interface PaymentConfigElementValue {
    paymentProviderKey: string | null;
    purpose: string | null;
    description: string | null;
    mapRequestor: boolean | null;
    requestorMapping: PaymentConfigElementValueRequestorMapping | null;
    items: PaymentConfigElementValueItem[] | null;
}

export interface PaymentConfigElementValueRequestorMapping {
    requestorSourceType: 'fixPerson' | 'fixOrg' | 'processDataKey' | null;
    lastNameDestinationKey: string | null;
    firstNameDestinationKey: string | null;
    genderDestinationKey: string | null;
    isOrganizationDestinationKey: string | null;
    organizationNameDestinationKey: string | null;
    streetDestinationKey: string | null;
    houseNumberDestinationKey: string | null;
    addressLineDestinationKey: string | null;
    postalCodeDestinationKey: string | null;
    cityDestinationKey: string | null;
    countryDestinationKey: string | null;
}

export interface PaymentConfigElementValueItem {
    idType: PaymentConfigElementValueItemIdType | null;
    predefinedId: string | null;
    description: string | null;
    reference: string | null;
    costType: PaymentConfigElementValueItemCostType | null;
    fixedCosts: number | null;
    variableCostsCalculationType: PaymentConfigElementValueItemVariableValueCalculationType | null;
    variableCostsNoCodeCalculation: NoCodeOperand | null;
    variableCostsLowCodeCalculation: JavascriptCode | null;
    quantityType: PaymentConfigElementValueItemQuantityType | null;
    fixedQuantity: number | null;
    variableQuantityCalculationType: PaymentConfigElementValueItemVariableValueCalculationType | null;
    variableQuantityNoCodeCalculation: NoCodeOperand | null;
    variableQuantityLowCodeCalculation: JavascriptCode | null;
    fixedTaxRate: number | null;
    additionalBookingData: Record<string, string> | null;
}

export enum PaymentConfigElementValueItemIdType {
    AutoGeneratedUUID = 'AutoGeneratedUUID',
    Predefined = 'Predefined',
}

export enum PaymentConfigElementValueItemCostType {
    FixedCosts = 'FixedCosts',
    VariableCosts = 'VariableCosts',
}

export enum PaymentConfigElementValueItemQuantityType {
    FixedQuantity = 'FixedQuantity',
    VariableQuantity = 'VariableQuantity',
}

export enum PaymentConfigElementValueItemVariableValueCalculationType {
    NoCode = 'NoCode',
    LowCode = 'LowCode',
}
