-- create example departments
insert into departments (id,
                         name,
                         address,
                         imprint,
                         common_privacy,
                         common_accessibility,
                         technical_support_address,
                         special_support_address,
                         department_mail,
                         theme_id,
                         technical_support_phone,
                         technical_support_info,
                         special_support_phone,
                         special_support_info,
                         additional_info,
                         parent_department_id,
                         created,
                         updated)
values (1,
        'Verwaltungsgemeinschaft',
        E'Marktplatz 1\n12345 Grünberg',
        'Impressum der Verwaltungsgemeinschaft Bergwald',
        'Datenschutzhinweis der Verwaltungsgemeinschaft Bergwald',
        'Barrierefreiheitshinweis der Verwaltungsgemeinschaft Bergwald',
        'edv@vg-bergwald.de',
        'info@vg-bergwald.de',
        null,
        1,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zur Verwaltungsgemeinschaft Bergwald finden Sie auf der <a href="https://vg-bergwald.de">Webseite</a>.',
        null,
        now(),
        now()),
       (2,
        'EDV',
        null,
        null,
        null,
        null,
        null,
        'edv@vg-bergwald.de',
        null,
        null,
        null,
        null,
        '+49 2405 404-2',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (3,
        'Kämmerei',
        null,
        null,
        null,
        null,
        null,
        'finanzen@vg-bergwald.de',
        null,
        null,
        null,
        null,
        '+49 2405 404-3',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (4,
        'Liegenschaften',
        null,
        null,
        null,
        null,
        null,
        'liegenschaften@vg-bergwald.de',
        null,
        null,
        null,
        null,
        '+49 2405 404-4',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (5,
        'Ordnungsamt',
        null,
        null,
        null,
        null,
        null,
        'ordnungsamt@vg-bergwald.de',
        null,
        null,
        null,
        null,
        '+49 2405 404-5',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        null,
        1,
        now(),
        now()),
       (6,
        'Stadt Grünberg',
        E'Marktplatz 1\n12345 Grünberg',
        'Impressum der Stadt Grünberg',
        'Datenschutzhinweis der Stadt Grünberg',
        'Barrierefreiheitshinweis der Stadt Grünberg',
        'edv@vg-bergwald.de',
        'info@gruenberg.de',
        null,
        2,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Die Stadt Grünberg ist Teil der Verwaltungsgemeinschaft Bergwald. Weitere Informationen zur Verwaltungsgemeinschaft Bergwald finden Sie auf der <a href="https://vg-bergwald.de">Webseite</a>.',
        null,
        now(),
        now()),
       (7,
        'Kita Grüngras',
        E'Grasweg 2\n12345 Grünberg',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        6,
        now(),
        now()),
       (8,
        'Gemeinde Blauheim',
        E'An der Goldgrube 4\n54321 Blauheim',
        'Impressum der Gemeinde Blauheim',
        'Datenschutzhinweis der Gemeinde Blauheim',
        'Barrierefreiheitshinweis der Gemeinde Blauheim',
        'edv@vg-bergwald.de',
        'info@blauheim.de',
        null,
        3,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Die Gemeinde Blauheim ist Teil der Verwaltungsgemeinschaft Bergwald. Weitere Informationen zur Verwaltungsgemeinschaft Bergwald finden Sie auf der <a href="https://vg-bergwald.de">Webseite</a>.',
        null,
        now(),
        now()),
       (9,
        'Kita Blaubeeren',
        E'Beerenweg 5\n54321 Blauheim',
        null,
        null,
        null,
        null,
        'info@kita-blaubeere.de',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        8,
        now(),
        now()),
       (10,
        'Kommune Rotfeld',
        E'Im Einöd 3\n32154 Rotfeld',
        'Impressum der Kommune Rotfeld',
        'Datenschutzhinweis der Kommune Rotfeld',
        'Barrierefreiheitshinweis der Kommune Rotfeld',
        'edv@vg-bergwald.de',
        'info@rotfeld.de',
        null,
        4,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Die Kommune Rotfeld ist Teil der Verwaltungsgemeinschaft Bergwald. Weitere Informationen zur Verwaltungsgemeinschaft Bergwald finden Sie auf der <a href="https://vg-bergwald.de">Webseite</a>.',
        null,
        now(),
        now())
on conflict (id) do update
    set name                      = excluded.name,
        address                   = excluded.address,
        imprint                   = excluded.imprint,
        common_privacy            = excluded.common_privacy,
        common_accessibility      = excluded.common_accessibility,
        technical_support_address = excluded.technical_support_address,
        special_support_address   = excluded.special_support_address,
        department_mail           = excluded.department_mail,
        theme_id                  = excluded.theme_id,
        technical_support_phone   = excluded.technical_support_phone,
        technical_support_info    = excluded.technical_support_info,
        special_support_phone     = excluded.special_support_phone,
        special_support_info      = excluded.special_support_info,
        additional_info           = excluded.additional_info,
        parent_department_id      = excluded.parent_department_id,
        updated                   = now();

-- fix id sequence for departments
select setval('departments_id_seq',
              (select max(id) from departments));