package de.aivot.gover.backend.elements.models.elements.form.input;

import de.aivot.gover.backend.core.services.ObjectMapperFactory;
import de.aivot.gover.backend.exceptions.ValidationException;
import de.aivot.gover.backend.javascript.models.JavascriptCode;
import de.aivot.gover.backend.nocode.models.NoCodeOperand;
import de.aivot.gover.backend.nocode.models.NoCodeReference;
import de.aivot.gover.backend.nocode.models.NoCodeStaticValue;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class PaymentConfigElementValueValidationTest {
    @Test
    void shouldValidateFixedPaymentItem() {
        assertDoesNotThrow(() -> fixedItem().performValidation());
    }

    @Test
    void shouldValidateVariablePaymentItem() {
        assertDoesNotThrow(() -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.VariableCosts,
                null,
                PaymentConfigElementValueItem.VariableValueCalculationType.NoCode,
                NoCodeStaticValue.of(BigDecimal.TEN),
                null,
                PaymentConfigElementValueItem.QuantityType.VariableQuantity,
                null,
                PaymentConfigElementValueItem.VariableValueCalculationType.LowCode,
                null,
                JavascriptCode.of("1"),
                BigDecimal.ZERO,
                null
        ).performValidation());
    }

    @Test
    void shouldRejectInvalidPaymentItems() {
        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.Predefined,
                null,
                PaymentConfigElementValueItem.CostType.FixedCosts,
                BigDecimal.ONE,
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.VariableCosts,
                null,
                null,
                NoCodeStaticValue.of(BigDecimal.ONE),
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.VariableCosts,
                null,
                PaymentConfigElementValueItem.VariableValueCalculationType.NoCode,
                NoCodeReference.of(null),
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.FixedCosts,
                new BigDecimal("-0.01"),
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.FixedCosts,
                BigDecimal.ONE,
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                new BigDecimal("100.01"),
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.FixedCosts,
                BigDecimal.ONE,
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                Map.of("", "value")
        ).performValidation());
    }

    @Test
    void shouldValidateRequestorMapping() {
        assertDoesNotThrow(() -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixPerson,
                "requestor.lastName",
                "requestor.firstName",
                "requestor.gender",
                null,
                null,
                "requestor.street",
                "requestor.houseNumber",
                "requestor.addressLine",
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());

        assertDoesNotThrow(() -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg,
                null,
                null,
                null,
                null,
                "requestor.organizationName",
                "requestor.street",
                "requestor.houseNumber",
                "requestor.addressLine",
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());

        assertDoesNotThrow(() -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                "requestor.lastName",
                "requestor.firstName",
                "requestor.gender",
                "requestor.isOrganization",
                "requestor.organizationName",
                "requestor.street",
                "requestor.houseNumber",
                "requestor.addressLine",
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());
    }

    @Test
    void shouldRoundTripRequestorMappingJson() throws Exception {
        var objectMapper = ObjectMapperFactory.getInstance();

        var mapping = objectMapper.readValue("""
                {
                  "requestorSourceType": "fixOrg",
                  "organizationNameDestinationKey": "requestor.organizationName",
                  "streeDestinationKey": "requestor.street",
                  "houseNumberDestinationKey": "requestor.houseNumber",
                  "addressLineDestinationKey": "requestor.addressLine",
                  "postalCodeDestinationKey": "requestor.postalCode",
                  "cityDestinationKey": "requestor.city",
                  "countryDestinationKey": "requestor.country"
                }
                """, PaymentConfigElementValueRequestorMapping.class);

        assertEquals(PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg, mapping.requestorSourceType());
        assertEquals("requestor.street", mapping.streetDestinationKey());

        var serialized = objectMapper.readValue(
                objectMapper.writeValueAsString(mapping),
                PaymentConfigElementValueRequestorMapping.class
        );

        assertEquals(PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg, serialized.requestorSourceType());
        assertEquals("requestor.street", serialized.streetDestinationKey());
    }

    @Test
    void shouldRejectDynamicRequestorMappingWithoutOrganizationFlag() {
        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                "requestor.lastName",
                "requestor.firstName",
                null,
                null,
                "requestor.organizationName",
                "requestor.street",
                "requestor.houseNumber",
                "requestor.addressLine",
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());
    }

    @Test
    void shouldRejectRequestorMappingWithoutVisibleGenderField() {
        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixPerson,
                "requestor.lastName",
                "requestor.firstName",
                null,
                null,
                null,
                "requestor.street",
                "requestor.houseNumber",
                "requestor.addressLine",
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());
    }

    @Test
    void shouldRejectRequestorMappingWithoutVisibleAddressLineField() {
        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg,
                null,
                null,
                null,
                null,
                "requestor.organizationName",
                "requestor.street",
                "requestor.houseNumber",
                null,
                "requestor.postalCode",
                "requestor.city",
                "requestor.country"
        ).performValidation());
    }

    @Test
    void shouldRejectInvalidRequestorMappings() {
        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                null,
                "requestor.lastName",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        ).performValidation());

        assertThrows(ValidationException.class, () -> new PaymentConfigElementValueRequestorMapping(
                PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                "requestor-lastName",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        ).performValidation());
    }

    private static PaymentConfigElementValueItem fixedItem() {
        return item(
                PaymentConfigElementValueItem.IdType.Predefined,
                "fee-1",
                PaymentConfigElementValueItem.CostType.FixedCosts,
                BigDecimal.ONE,
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        );
    }

    private static PaymentConfigElementValueItem item(
            PaymentConfigElementValueItem.IdType idType,
            String predefinedId,
            PaymentConfigElementValueItem.CostType costType,
            BigDecimal fixedCosts,
            PaymentConfigElementValueItem.VariableValueCalculationType variableCostsCalculationType,
            NoCodeOperand variableCostsNoCodeCalculation,
            JavascriptCode variableCostsLowCodeCalculation,
            PaymentConfigElementValueItem.QuantityType quantityType,
            Long fixedQuantity,
            PaymentConfigElementValueItem.VariableValueCalculationType variableQuantityCalculationType,
            NoCodeOperand variableQuantityNoCodeCalculation,
            JavascriptCode variableQuantityLowCodeCalculation,
            BigDecimal fixedTaxRate,
            Map<String, String> additionalBookingData
    ) {
        return new PaymentConfigElementValueItem(
                idType,
                predefinedId,
                "Description",
                "Reference",
                costType,
                fixedCosts,
                variableCostsCalculationType,
                variableCostsNoCodeCalculation,
                variableCostsLowCodeCalculation,
                quantityType,
                fixedQuantity,
                variableQuantityCalculationType,
                variableQuantityNoCodeCalculation,
                variableQuantityLowCodeCalculation,
                fixedTaxRate,
                additionalBookingData
        );
    }
}
