export interface VDepartmentUserRoleAssignmentWithDetailsEntity {
    id: number;
    departmentId: number;
    userId: string;
    created: string;
    updated: string;
    name: string;
    address?: string | null;
    imprint?: string | null;
    commonPrivacy?: string | null;
    commonAccessibility?: string | null;
    technicalSupportAddress?: string | null;
    specialSupportAddress?: string | null;
    departmentMail?: string | null;
    themeId?: number | null;
    technicalSupportPhone?: string | null;
    technicalSupportInfo?: string | null;
    specialSupportPhone?: string | null;
    specialSupportInfo?: string | null;
    additionalInfo?: string | null;
    depth: number;
    parentDepartmentId?: number | null;
    parentNames?: string[] | null;
    parentIds?: number[] | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    fullName?: string | null;
    enabled?: boolean | null;
    verified?: boolean | null;
    globalAdmin?: boolean | null;
    deletedInIdp?: boolean | null;
    userRoleAssignmentId?: number | null;
    userRoleId?: number | null;
    userRoleName?: string | null;
    description?: string | null;
    departmentPermissionEdit?: boolean | null;
    teamPermissionEdit?: boolean | null;
    formPermissionCreate?: boolean | null;
    formPermissionRead?: boolean | null;
    formPermissionEdit?: boolean | null;
    formPermissionDelete?: boolean | null;
    formPermissionAnnotate?: boolean | null;
    formPermissionPublish?: boolean | null;
    processPermissionCreate?: boolean | null;
    processPermissionRead?: boolean | null;
    processPermissionEdit?: boolean | null;
    processPermissionDelete?: boolean | null;
    processPermissionAnnotate?: boolean | null;
    processPermissionPublish?: boolean | null;
    processInstancePermissionCreate?: boolean | null;
    processInstancePermissionRead?: boolean | null;
    processInstancePermissionEdit?: boolean | null;
    processInstancePermissionDelete?: boolean | null;
    processInstancePermissionAnnotate?: boolean | null;
}

