server {
    listen      80;
    listen      [::]:80;
    server_name default_server;
    server_tokens off;

    root  /app/www;
    index index.html;

    gzip       on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /staff {
        try_files  $uri /staff/index.html;
    }

    location / {
        try_files  $uri /index.html;
    }

    location /index.html {
        expires off;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Expires "0" always;
        internal; # This is important to allow the internal redirect to work
    }

    location /staff/index.html {
        expires    -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        internal; # This is important to allow the internal redirect to work
    }

    location = /security.txt {
        return 301 /.well-known/security.txt;
    }
}