name: prosuna

services:
  prosuna_api:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: serve
    depends_on:
      - prosuna_database
      - keycloak
      - clamav
      - redis
      - rabbitmq
      - gotenberg
    environment:
      PROSUNA_SERVER_PORT: 9595
      PROSUNA_DB_HOST: prosuna_database
      PROSUNA_DB_PORT: 5432
      PROSUNA_DB_USERNAME: prosuna
      PROSUNA_DB_PASSWORD: ${PROSUNA_DB_PASSWORD}
      PROSUNA_DB_DATABASE: prosuna
      PROSUNA_REDIS_HOST: redis
      PROSUNA_REDIS_PORT: 6379
      PROSUNA_REDIS_DATABASE: 0
      PROSUNA_SMTP_HOST: ${PROSUNA_SMTP_HOST}
      PROSUNA_SMTP_PORT: ${PROSUNA_SMTP_PORT}
      PROSUNA_SMTP_AUTH: ${PROSUNA_SMTP_AUTH:-true}
      PROSUNA_SMTP_TLS: ${PROSUNA_SMTP_TLS:-true}
      PROSUNA_SMTP_USERNAME: ${PROSUNA_SMTP_USERNAME}
      PROSUNA_SMTP_PASSWORD: ${PROSUNA_SMTP_PASSWORD}
      PROSUNA_RABBITMQ_HOST: rabbitmq
      PROSUNA_RABBITMQ_PORT: 5672
      PROSUNA_RABBITMQ_USERNAME: prosuna
      PROSUNA_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PROSUNA_CLAM_HOST: clamav
      PROSUNA_CLAM_PORT: 3310
      PROSUNA_GOTENBERG_HOST: gotenberg
      PROSUNA_GOTENBERG_PORT: 3000
      PROSUNA_KEYCLOAK_OIDC_HOSTNAME: ${PROSUNA_HOSTNAME}/idp
      PROSUNA_KEYCLOAK_OIDC_INTERNAL_HOSTNAME: http://keycloak:8080/idp
      PROSUNA_KEYCLOAK_OIDC_REALM: staff
      PROSUNA_KEYCLOAK_OIDC_FRONTEND_CLIENT_ID: app
      PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_ID: backend
      PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET: ${PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
      PROSUNA_SECRETS_KEY: ${PROSUNA_SECRETS_KEY}
      PROSUNA_CAPTCHA_KEY: ${PROSUNA_CAPTCHA_KEY}
      PROSUNA_HOSTNAME: ${PROSUNA_HOSTNAME}
      PROSUNA_SUPPORT_URL: ${PROSUNA_SUPPORT_URL:-}
      PROSUNA_TIMEZONE: Europe/Berlin
      PROSUNA_FROM_MAIL: ${PROSUNA_FROM_MAIL}
      PROSUNA_REPORT_MAIL: ${PROSUNA_REPORT_MAIL}
      PROSUNA_BOOTSTRAP_ADMIN_MAIL: ${PROSUNA_BOOTSTRAP_ADMIN_MAIL}
    volumes:
      - prosuna_data:/app/data
    networks:
      - prosuna
      - prosuna_keycloak
      - proxy

  prosuna_app:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: web
    depends_on:
      prosuna_api:
        condition: service_healthy
        restart: true
      gotenberg:
        condition: service_started
        restart: true
    environment:
      PROSUNA_HOSTNAME: ${PROSUNA_HOSTNAME}
    networks:
      - proxy

  prosuna_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PROSUNA_DB_PASSWORD}
      POSTGRES_USER: prosuna
      POSTGRES_DB: prosuna
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: Europe/Berlin
    volumes:
      - prosuna_database_data:/var/lib/postgresql/data
    networks:
      - prosuna

  keycloak:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins:26.6.4.2
    restart: unless-stopped
    depends_on:
      - keycloak_database
    command: start
    environment:
      KC_HOSTNAME: ${PROSUNA_HOSTNAME}/idp
      KC_HTTP_RELATIVE_PATH: /idp
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_FEATURES: transient-users,update-email,hostname:v2
    networks:
      - keycloak
      - prosuna_keycloak
      - proxy

  keycloak_setup:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins-setup:0.0.24
    restart: on-failure
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080/idp
      HOSTNAME: ${PROSUNA_HOSTNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KEYCLOAK_DEPLOYMENT_CLIENT_NAME: deployment
      KEYCLOAK_DEPLOYMENT_CLIENT_SECRET: ${KEYCLOAK_DEPLOYMENT_CLIENT_SECRET}
      KEYCLOAK_ADMIN_EMAIL: ${KEYCLOAK_ADMIN_EMAIL}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      LOGGING_LEVEL_HTTP: ERROR
      SMTP_HOST: ${PROSUNA_SMTP_HOST}
      SMTP_PORT: ${PROSUNA_SMTP_PORT}
      SMTP_USERNAME: ${PROSUNA_SMTP_USERNAME}
      SMTP_PASSWORD: ${PROSUNA_SMTP_PASSWORD}
      SMTP_FROM: ${PROSUNA_FROM_MAIL}
      SMTP_FROM_DISPLAY: Prosuna IdP
      BACKEND_CLIENT_SECRET: ${PROSUNA_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
    networks:
      - keycloak

  keycloak_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_database_data:/var/lib/postgresql/data
    networks:
      - keycloak

  clamav:
    image: docker.io/clamav/clamav:1.5-debian
    restart: unless-stopped
    networks:
      - prosuna

  redis:
    image: docker.io/redis:8-alpine
    restart: unless-stopped
    networks:
      - prosuna

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    depends_on:
      prosuna_api:
        condition: service_started
        restart: true
    environment:
      CHROMIUM_DENY_PRIVATE_IPS: "true"
      CHROMIUM_DENY_PUBLIC_IPS: "true"
      CHROMIUM_ALLOW_LIST: "^(https://${PROSUNA_HOSTNAME_REGEX}/|file:///tmp/)"
    networks:
      - prosuna

  rabbitmq:
    image: docker.io/rabbitmq:4-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: prosuna
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - prosuna

  caddy:
    image: docker.io/caddy:2-alpine
    restart: unless-stopped
    depends_on:
      prosuna_api:
        condition: service_healthy
        restart: true
      prosuna_app:
        condition: service_healthy
        restart: true
    environment:
      PROSUNA_HOSTNAME: ${PROSUNA_HOSTNAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy


volumes:
  prosuna_data:
  prosuna_database_data:
  keycloak_database_data:
  rabbitmq_data:
  caddy_data:
  caddy_config:


networks:
  prosuna:
  keycloak:
  prosuna_keycloak:
  proxy:
