name: gover

services:
  gover_api:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: serve
    depends_on:
      - gover_database
      - keycloak
      - clamav
      - redis
      - rabbitmq
      - gotenberg
    environment:
      GOVER_SERVER_PORT: 9595
      GOVER_DB_HOST: gover_database
      GOVER_DB_PORT: 5432
      GOVER_DB_USERNAME: gover
      GOVER_DB_PASSWORD: ${GOVER_DB_PASSWORD}
      GOVER_DB_DATABASE: gover
      GOVER_REDIS_HOST: redis
      GOVER_REDIS_PORT: 6379
      GOVER_REDIS_DATABASE: 0
      GOVER_SMTP_HOST: ${GOVER_SMTP_HOST}
      GOVER_SMTP_PORT: ${GOVER_SMTP_PORT}
      GOVER_SMTP_AUTH: ${GOVER_SMTP_AUTH:-true}
      GOVER_SMTP_TLS: ${GOVER_SMTP_TLS:-true}
      GOVER_SMTP_USERNAME: ${GOVER_SMTP_USERNAME}
      GOVER_SMTP_PASSWORD: ${GOVER_SMTP_PASSWORD}
      GOVER_RABBITMQ_HOST: rabbitmq
      GOVER_RABBITMQ_PORT: 5672
      GOVER_RABBITMQ_USERNAME: gover
      GOVER_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      GOVER_CLAM_HOST: clamav
      GOVER_CLAM_PORT: 3310
      GOVER_GOTENBERG_HOST: gotenberg
      GOVER_GOTENBERG_PORT: 3000
      GOVER_KEYCLOAK_OIDC_HOSTNAME: ${GOVER_HOSTNAME}/idp
      GOVER_KEYCLOAK_OIDC_INTERNAL_HOSTNAME: http://keycloak:8080/idp
      GOVER_KEYCLOAK_OIDC_REALM: staff
      GOVER_KEYCLOAK_OIDC_FRONTEND_CLIENT_ID: app
      GOVER_KEYCLOAK_OIDC_BACKEND_CLIENT_ID: backend
      GOVER_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET: ${GOVER_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
      GOVER_SECRETS_KEY: ${GOVER_SECRETS_KEY}
      GOVER_CAPTCHA_KEY: ${GOVER_CAPTCHA_KEY}
      GOVER_HOSTNAME: ${GOVER_HOSTNAME}
      GOVER_TIMEZONE: Europe/Berlin
      GOVER_FROM_MAIL: ${GOVER_FROM_MAIL}
      GOVER_REPORT_MAIL: ${GOVER_REPORT_MAIL}
      GOVER_BOOTSTRAP_ADMIN_MAIL: ${GOVER_BOOTSTRAP_ADMIN_MAIL}
    volumes:
      - gover_data:/app/data
    networks:
      - gover
      - gover_keycloak
      - proxy

  gover_app:
    image: ghcr.io/aivot-digital/gover-next:5.0.0-beta-131
    restart: unless-stopped
    command: web
    depends_on:
      gover_api:
        condition: service_healthy
        restart: true
      gotenberg:
        condition: service_started
        restart: true
    environment:
      GOVER_HOSTNAME: ${GOVER_HOSTNAME}
    networks:
      - proxy

  gover_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${GOVER_DB_PASSWORD}
      POSTGRES_USER: gover
      POSTGRES_DB: gover
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: Europe/Berlin
    volumes:
      - gover_database_data:/var/lib/postgresql/data
    networks:
      - gover

  keycloak:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins:26.6.4.0
    restart: unless-stopped
    depends_on:
      - keycloak_database
    command: start
    environment:
      KC_HOSTNAME: ${GOVER_HOSTNAME}/idp
      KC_HTTP_RELATIVE_PATH: /idp
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_FEATURES: transient-users,update-email,hostname:v2
    networks:
      - keycloak
      - gover_keycloak
      - proxy

  keycloak_setup:
    image: ghcr.io/aivot-digital/keycloak-egov-plugins-setup:0.0.23
    restart: on-failure
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080/idp
      HOSTNAME: ${GOVER_HOSTNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KEYCLOAK_DEPLOYMENT_CLIENT_NAME: deployment
      KEYCLOAK_DEPLOYMENT_CLIENT_SECRET: ${KEYCLOAK_DEPLOYMENT_CLIENT_SECRET}
      KEYCLOAK_ADMIN_EMAIL: ${KEYCLOAK_ADMIN_EMAIL}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      LOGGING_LEVEL_HTTP: ERROR
      SMTP_HOST: ${GOVER_SMTP_HOST}
      SMTP_PORT: ${GOVER_SMTP_PORT}
      SMTP_USERNAME: ${GOVER_SMTP_USERNAME}
      SMTP_PASSWORD: ${GOVER_SMTP_PASSWORD}
      SMTP_FROM: ${GOVER_FROM_MAIL}
      SMTP_FROM_DISPLAY: Gover IDP
      BACKEND_CLIENT_SECRET: ${GOVER_KEYCLOAK_OIDC_BACKEND_CLIENT_SECRET}
    networks:
      - keycloak

  keycloak_database:
    image: docker.io/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_database_data:/var/lib/postgresql/data
    networks:
      - keycloak

  clamav:
    image: docker.io/clamav/clamav:1.5-debian
    restart: unless-stopped
    networks:
      - gover

  redis:
    image: docker.io/redis:8-alpine
    restart: unless-stopped
    networks:
      - gover

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    depends_on:
      gover_api:
        condition: service_started
        restart: true
    environment:
      CHROMIUM_DENY_PRIVATE_IPS: "true"
      CHROMIUM_DENY_PUBLIC_IPS: "true"
      CHROMIUM_ALLOW_LIST: "^(https://${GOVER_HOSTNAME_REGEX}/|file:///tmp/)"
    networks:
      - gover

  rabbitmq:
    image: docker.io/rabbitmq:4-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: gover
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gover

  caddy:
    image: docker.io/caddy:2-alpine
    restart: unless-stopped
    depends_on:
      gover_api:
        condition: service_healthy
        restart: true
      gover_app:
        condition: service_healthy
        restart: true
    environment:
      GOVER_HOSTNAME: ${GOVER_HOSTNAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy


volumes:
  gover_data:
  gover_database_data:
  keycloak_database_data:
  rabbitmq_data:
  caddy_data:
  caddy_config:


networks:
  gover:
  keycloak:
  gover_keycloak:
  proxy:
