package de.aivot.gover.backend.elements.models.elements.form.input;

import de.aivot.gover.backend.exceptions.ValidationException;
import de.aivot.gover.backend.javascript.models.JavascriptCode;
import de.aivot.gover.backend.nocode.models.NoCodeOperand;
import jakarta.annotation.Nullable;

import java.math.BigDecimal;
import java.util.Map;

public record PaymentConfigElementValueItem(
        @Nullable
        IdType idType,
        @Nullable
        String predefinedId,

        @Nullable
        String description, // Supports Template Tag Rendering

        @Nullable
        String reference, // Supports Template Tag Rendering

        // Costs of this payment item (single item, netto)
        @Nullable
        CostType costType,
        @Nullable
        BigDecimal fixedCosts,
        @Nullable
        VariableValueCalculationType variableCostsCalculationType,
        @Nullable
        NoCodeOperand variableCostsNoCodeCalculation,
        @Nullable
        JavascriptCode variableCostsLowCodeCalculation,

        // Quantity of this payment item
        @Nullable
        QuantityType quantityType,
        @Nullable
        Long fixedQuantity,
        @Nullable
        VariableValueCalculationType variableQuantityCalculationType,
        @Nullable
        NoCodeOperand variableQuantityNoCodeCalculation,
        @Nullable
        JavascriptCode variableQuantityLowCodeCalculation,

        // More information for this payment item
        @Nullable
        BigDecimal fixedTaxRate,
        @Nullable
        Map<String, String> additionalBookingData // Value Field Supports Template Tag Rendering
) {
    public void performValidation() throws ValidationException {
        // TODO
    }

    public enum IdType {
        AutoGeneratedUUID,
        Predefined
    }

    public enum CostType {
        FixedCosts,
        VariableCosts,
    }

    public enum QuantityType {
        FixedQuantity,
        VariableQuantity
    }

    public enum VariableValueCalculationType {
        NoCode,
        LowCode,
    }
}
