-- create example departments
insert into departments (id,
                         name,
                         address,
                         imprint,
                         common_privacy,
                         common_accessibility,
                         technical_support_address,
                         special_support_address,
                         department_mail,
                         theme_id,
                         technical_support_phone,
                         technical_support_info,
                         special_support_phone,
                         special_support_info,
                         additional_info,
                         parent_department_id,
                         created,
                         updated)
values (1,
        'Stadt Bad Musterstadt',
        E'Seestraße 1a\n12345 Bad Musterstadt',
        'Impressum der Stadt Bad Musterstadt',
        'Datenschutzhinweis der Stadt Bad Musterstadt',
        'Barrierefreiheitshinweis der Stadt Bad Musterstadt',
        'it@example.com',
        'info@example',
        null,
        1,
        '+49 2405 404-1',
        'Mo. bis Fr. 10:00 Uhr bis 16:00 Uhr',
        '+49 2405 404-2',
        'Mo. bis Fr. 08:00 Uhr bis 12:00 Uhr',
        'Weitere Informationen zur Stadt Bad Musterstadt finden Sie auf der <a href="https://example.com">Webseite</a>.',
        null,
        now(),
        now()),
       (2,
        'FB 1 - Bürgerservice',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (3,
        'FB 2 - Umwelt und Bauen',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (4,
        'FB 3 - Bildung, Familie und Kultur',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (5,
        'FB 4 - Innerer Service',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        now(),
        now()),
       (6,
        'FD 1/30 - Ordnung u. Einwohnerservice',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        now(),
        now()),
       (7,
        'FD 2/63 - Bauaufsicht',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3,
        now(),
        now()),
       (8,
        'FD 3/41 - Kinder, Jugend und Familie',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4,
        now(),
        now()),
       (9,
        'FD 4/51 - Personal',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        5,
        now(),
        now()),
       (10,
        'FD 4/52 - Finanzen',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        5,
        now(),
        now())
on conflict (id) do update
    set name                      = excluded.name,
        address                   = excluded.address,
        imprint                   = excluded.imprint,
        common_privacy            = excluded.common_privacy,
        common_accessibility      = excluded.common_accessibility,
        technical_support_address = excluded.technical_support_address,
        special_support_address   = excluded.special_support_address,
        department_mail           = excluded.department_mail,
        theme_id                  = excluded.theme_id,
        technical_support_phone   = excluded.technical_support_phone,
        technical_support_info    = excluded.technical_support_info,
        special_support_phone     = excluded.special_support_phone,
        special_support_info      = excluded.special_support_info,
        additional_info           = excluded.additional_info,
        parent_department_id      = excluded.parent_department_id,
        updated                   = now();

-- fix id sequence for departments
select setval('departments_id_seq',
              (select max(id) from departments));

-- assign the default vendor name
insert into system_configs (key,
                            value)
values ('ProviderName', 'Stadt Bad Musterstadt')
on conflict (key) do update
    set value = excluded.value;