-- create example links for the staff dashboard
insert into custom_links (id,
                          label,
                          description,
                          url,
                          icon,
                          type,
                          position,
                          enabled,
                          created,
                          updated)
values (1,
        'Mitarbeitendenportal',
        'Interne Nachrichten, Kontakte und zentrale Dienste',
        'https://example.com/mitarbeitendenportal',
        'intranet',
        0,
        0,
        true,
        now(),
        now()),
       (2,
        'Dienstanweisungen',
        'Aktuelle Regelungen und Arbeitshilfen der Stadtverwaltung',
        'https://example.com/dienstanweisungen',
        'documentation',
        0,
        1,
        true,
        now(),
        now()),
       (3,
        'Status der Online-Dienste',
        'Verfügbarkeit der städtischen Fachverfahren und Portale',
        'https://status.example.com',
        'status',
        0,
        2,
        true,
        now(),
        now())
on conflict (id) do update
    set label       = excluded.label,
        description = excluded.description,
        url         = excluded.url,
        icon        = excluded.icon,
        type        = excluded.type,
        position    = excluded.position,
        enabled     = excluded.enabled,
        updated     = now();

select setval('custom_links_id_seq',
              (select max(id) from custom_links));
