spring.datasource.url=jdbc:postgresql://gover-database:5432/gover
spring.datasource.username=gover
spring.datasource.password=gover

spring.mail.host=smtp.aivot.de
spring.mail.port=465
spring.mail.username=gover@aivot.de
spring.mail.password=not-the-real-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gover.reportMail=gover@aivot.de
