spring.datasource.url=jdbc:postgresql://db:5432/gover
spring.datasource.username=gover
spring.datasource.password=gover

server.servlet.context-path=/api

minio.url=http://minio:9000
minio.access=gover
minio.secret=gover_secret_key
minio.bucket=gover

smtp.host=<SMTP_HOST>
smtp.port=<SMTP_PORT>
smtp.username=<SMTP_USERNAME>
smtp.password=<SMTP_PASSWORD>
smtp.useTls=true
