package de.aivot.gover.backend.elements.models.elements.form.input;

import de.aivot.gover.backend.core.services.ObjectMapperFactory;
import de.aivot.gover.backend.exceptions.ValidationException;
import de.aivot.gover.backend.javascript.models.JavascriptCode;
import de.aivot.gover.backend.nocode.models.NoCodeOperand;
import de.aivot.gover.backend.nocode.models.NoCodeReference;
import de.aivot.gover.backend.nocode.models.NoCodeStaticValue;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class PaymentConfigElementValueValidationTest {
    @Test
    void shouldValidateFixedPaymentItem() {
        assertEquals(Map.of(), fixedItem().performValidation());
    }

    @Test
    void shouldValidateVariablePaymentItem() {
        assertEquals(Map.of(), item(
                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                null,
                PaymentConfigElementValueItem.CostType.VariableCosts,
                null,
                PaymentConfigElementValueItem.VariableValueCalculationType.NoCode,
                NoCodeStaticValue.of(BigDecimal.TEN),
                null,
                PaymentConfigElementValueItem.QuantityType.VariableQuantity,
                null,
                PaymentConfigElementValueItem.VariableValueCalculationType.LowCode,
                null,
                JavascriptCode.of("1"),
                BigDecimal.ZERO,
                null
        ).performValidation());
    }

    @Test
    void shouldRejectInvalidPaymentItems() {
        assertEquals(
                Map.of("predefinedId", "Vordefinierte ID muss angegeben werden."),
                item(
                        PaymentConfigElementValueItem.IdType.Predefined,
                        null,
                        PaymentConfigElementValueItem.CostType.FixedCosts,
                        BigDecimal.ONE,
                        null,
                        null,
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        BigDecimal.ZERO,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("variableCostsCalculationType", "Variable Kosten benötigen einen Berechnungstyp."),
                item(
                        PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                        null,
                        PaymentConfigElementValueItem.CostType.VariableCosts,
                        null,
                        null,
                        NoCodeStaticValue.of(BigDecimal.ONE),
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        BigDecimal.ZERO,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("variableCostsNoCodeCalculation", "Variable Kosten enthalten einen ungültigen No-Code-Ausdruck."),
                item(
                        PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                        null,
                        PaymentConfigElementValueItem.CostType.VariableCosts,
                        null,
                        PaymentConfigElementValueItem.VariableValueCalculationType.NoCode,
                        NoCodeReference.of(null),
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        BigDecimal.ZERO,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("fixedCosts", "Feste Kosten dürfen nicht negativ sein."),
                item(
                        PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                        null,
                        PaymentConfigElementValueItem.CostType.FixedCosts,
                        new BigDecimal("-0.01"),
                        null,
                        null,
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        BigDecimal.ZERO,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("fixedTaxRate", "Der Steuersatz muss zwischen 0 und 100 liegen."),
                item(
                        PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                        null,
                        PaymentConfigElementValueItem.CostType.FixedCosts,
                        BigDecimal.ONE,
                        null,
                        null,
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        new BigDecimal("100.01"),
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("additionalBookingData", "Buchungsdaten dürfen keine leeren Schlüssel enthalten."),
                item(
                        PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                        null,
                        PaymentConfigElementValueItem.CostType.FixedCosts,
                        BigDecimal.ONE,
                        null,
                        null,
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        1L,
                        null,
                        null,
                        null,
                        BigDecimal.ZERO,
                        Map.of("", "value")
                ).performValidation()
        );

        assertEquals(
                Map.of(
                        "predefinedId", "Vordefinierte ID muss angegeben werden.",
                        "fixedCosts", "Feste Kosten müssen angegeben werden.",
                        "fixedQuantity", "Feste Menge muss angegeben werden.",
                        "fixedTaxRate", "Es muss ein Steuersatz angegeben werden.",
                        "additionalBookingData", "Buchungsdaten dürfen keine leeren Schlüssel enthalten."
                ),
                item(
                        PaymentConfigElementValueItem.IdType.Predefined,
                        null,
                        PaymentConfigElementValueItem.CostType.FixedCosts,
                        null,
                        null,
                        null,
                        null,
                        PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                        null,
                        null,
                        null,
                        null,
                        null,
                        Map.of("", "value")
                ).performValidation()
        );
    }

    @Test
    void shouldKeepItemErrorDetailsIndexAligned() {
        var element = new PaymentConfigElement();

        var exception = assertThrows(ValidationException.class, () -> element.performValidation(new PaymentConfigElementValue(
                UUID.randomUUID(),
                "Purpose",
                "Description",
                false,
                null,
                List.of(
                        fixedItem(),
                        item(
                                PaymentConfigElementValueItem.IdType.AutoGeneratedUUID,
                                null,
                                PaymentConfigElementValueItem.CostType.FixedCosts,
                                null,
                                null,
                                null,
                                null,
                                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                                1L,
                                null,
                                null,
                                null,
                                BigDecimal.ZERO,
                                null
                        )
                ),
                null,
                null
        )));

        var errorDetails = (Map<?, ?>) exception.getErrorDetails();
        var itemErrors = (List<?>) errorDetails.get("items");

        assertEquals(2, itemErrors.size());
        assertNull(itemErrors.get(0));
        assertEquals(Map.of("fixedCosts", "Feste Kosten müssen angegeben werden."), itemErrors.get(1));
    }

    @Test
    void shouldValidateRequestorMapping() {
        assertEquals(
                Map.of(),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixPerson,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of(),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of(),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                        null,
                        null,
                        null,
                        "requestor.isOrganization",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );
    }

    @Test
    void shouldRoundTripRequestorMappingJson() throws Exception {
        var objectMapper = ObjectMapperFactory.getInstance();

        var mapping = objectMapper.readValue("""
                {
                  "requestorSourceType": "fixOrg",
                  "organizationNameDestinationKey": "requestor.organizationName",
                  "streeDestinationKey": "requestor.street",
                  "houseNumberDestinationKey": "requestor.houseNumber",
                  "addressLineDestinationKey": "requestor.addressLine",
                  "postalCodeDestinationKey": "requestor.postalCode",
                  "cityDestinationKey": "requestor.city",
                  "countryDestinationKey": "requestor.country"
                }
                """, PaymentConfigElementValueRequestorMapping.class);

        assertEquals(PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg, mapping.requestorSourceType());
        assertEquals("requestor.street", mapping.streetDestinationKey());

        var serialized = objectMapper.readValue(
                objectMapper.writeValueAsString(mapping),
                PaymentConfigElementValueRequestorMapping.class
        );

        assertEquals(PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg, serialized.requestorSourceType());
        assertEquals("requestor.street", serialized.streetDestinationKey());
    }

    @Test
    void shouldRejectDynamicRequestorMappingWithoutOrganizationFlag() {
        assertEquals(
                Map.of("isOrganizationDestinationKey", "Ist Organisation muss zugewiesen werden."),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                        "requestor.lastName",
                        "requestor.firstName",
                        null,
                        null,
                        "requestor.organizationName",
                        "requestor.street",
                        "requestor.houseNumber",
                        "requestor.addressLine",
                        "requestor.postalCode",
                        "requestor.city",
                        "requestor.country"
                ).performValidation()
        );
    }

    @Test
    void shouldAllowRequestorMappingWithoutVisibleGenderField() {
        assertEquals(
                Map.of(),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixPerson,
                        "requestor.lastName",
                        "requestor.firstName",
                        null,
                        null,
                        null,
                        "requestor.street",
                        "requestor.houseNumber",
                        "requestor.addressLine",
                        "requestor.postalCode",
                        "requestor.city",
                        "requestor.country"
                ).performValidation()
        );
    }

    @Test
    void shouldAllowRequestorMappingWithoutVisibleAddressLineField() {
        assertEquals(
                Map.of(),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.FixOrg,
                        null,
                        null,
                        null,
                        null,
                        "requestor.organizationName",
                        "requestor.street",
                        "requestor.houseNumber",
                        null,
                        "requestor.postalCode",
                        "requestor.city",
                        "requestor.country"
                ).performValidation()
        );
    }

    @Test
    void shouldRejectInvalidRequestorMappings() {
        assertEquals(
                Map.of("requestorSourceType", "Es muss eine Quelle für die Antragsteller-Zuweisung ausgewählt werden."),
                new PaymentConfigElementValueRequestorMapping(
                        null,
                        "requestor.lastName",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.of("isOrganizationDestinationKey", "Ist Organisation muss zugewiesen werden."),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );

        assertEquals(
                Map.ofEntries(
                        Map.entry("lastNameDestinationKey", "Nachname muss ein gültiger Prozessdaten-Schlüssel sein."),
                        Map.entry("isOrganizationDestinationKey", "Ist Organisation muss zugewiesen werden.")
                ),
                new PaymentConfigElementValueRequestorMapping(
                        PaymentConfigElementValueRequestorMapping.RequestorSourceType.ProcessDataKey,
                        "requestor-lastName",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null
                ).performValidation()
        );
    }

    private static PaymentConfigElementValueItem fixedItem() {
        return item(
                PaymentConfigElementValueItem.IdType.Predefined,
                "fee-1",
                PaymentConfigElementValueItem.CostType.FixedCosts,
                BigDecimal.ONE,
                null,
                null,
                null,
                PaymentConfigElementValueItem.QuantityType.FixedQuantity,
                1L,
                null,
                null,
                null,
                BigDecimal.ZERO,
                null
        );
    }

    private static PaymentConfigElementValueItem item(
            PaymentConfigElementValueItem.IdType idType,
            String predefinedId,
            PaymentConfigElementValueItem.CostType costType,
            BigDecimal fixedCosts,
            PaymentConfigElementValueItem.VariableValueCalculationType variableCostsCalculationType,
            NoCodeOperand variableCostsNoCodeCalculation,
            JavascriptCode variableCostsLowCodeCalculation,
            PaymentConfigElementValueItem.QuantityType quantityType,
            Long fixedQuantity,
            PaymentConfigElementValueItem.VariableValueCalculationType variableQuantityCalculationType,
            NoCodeOperand variableQuantityNoCodeCalculation,
            JavascriptCode variableQuantityLowCodeCalculation,
            BigDecimal fixedTaxRate,
            Map<String, String> additionalBookingData
    ) {
        return new PaymentConfigElementValueItem(
                idType,
                predefinedId,
                "Description",
                "Reference",
                costType,
                fixedCosts,
                variableCostsCalculationType,
                variableCostsNoCodeCalculation,
                variableCostsLowCodeCalculation,
                quantityType,
                fixedQuantity,
                variableQuantityCalculationType,
                variableQuantityNoCodeCalculation,
                variableQuantityLowCodeCalculation,
                fixedTaxRate,
                additionalBookingData
        );
    }
}
