package de.aivot.gover.backend.form.repositories;

import de.aivot.gover.backend.core.repositories.ReadOnlyRepository;
import de.aivot.gover.backend.form.entities.VFormVersionWithDetailsAndPermissionsEntity;
import de.aivot.gover.backend.form.entities.VFormVersionWithDetailsAndPermissionsEntityId;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface VFormVersionWithDetailsAndPermissionsRepository extends ReadOnlyRepository<VFormVersionWithDetailsAndPermissionsEntity, VFormVersionWithDetailsAndPermissionsEntityId>, JpaSpecificationExecutor<VFormVersionWithDetailsAndPermissionsEntity> {

}
