-- create example links for the staff dashboard
insert into custom_links (id,
                          label,
                          description,
                          url,
                          icon,
                          type,
                          position,
                          enabled,
                          created,
                          updated)
values (1,
        'Wissensportal',
        'Gemeinsame Arbeitshilfen und Vorlagen der Verwaltungsgemeinschaft',
        'https://example.com/wissensportal',
        'documentation',
        0,
        0,
        true,
        now(),
        now()),
       (2,
        'Sitzungskalender',
        'Termine und Unterlagen der Mitgliedskommunen',
        'https://example.com/sitzungskalender',
        'calendar',
        0,
        1,
        true,
        now(),
        now()),
       (3,
        'Kommunales Rechenzentrum',
        'Betriebsinformationen zu gemeinsam genutzten Diensten',
        'https://status.example.com',
        'status',
        0,
        2,
        true,
        now(),
        now())
on conflict (id) do update
    set label       = excluded.label,
        description = excluded.description,
        url         = excluded.url,
        icon        = excluded.icon,
        type        = excluded.type,
        position    = excluded.position,
        enabled     = excluded.enabled,
        updated     = now();

select setval('custom_links_id_seq',
              (select max(id) from custom_links));
