name: Generate library

on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          architecture: x64

      - name: Publish the package to the GitHub package registry
        working-directory: backend
        run: mvn --batch-mode deploy
        env:
          BUILD_VERSION: ${{ inputs.build_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
